type Example = [string, string];

const note = (word: string, split: string, tamilSound: string, tamil: string, meaning: string, kind: string, emoji: string, examples: Example[]) => ({ word, split, tamilSound, tamil, meaning, kind, emoji, examples });

export const classNoteCategories = [
  { id: 'class-plurals', section: 'class-notes' as const, name: 'Singular & Plural', tamil: 'ஒருமையும் பன்மையும்', emoji: '🔤', color: '#c06b4e', words: [
    note('Plural -S', 'book → books', 'ப்ளூரல் எஸ்', 'பன்மைக்கு -s சேர்த்தல்', 'Most nouns become plural by adding -s.', 'Class note · Plural rule', '📚', [['book → books', 'புத்தகம் → புத்தகங்கள்'], ['pen → pens', 'பேனா → பேனாக்கள்'], ['friend → friends', 'நண்பர் → நண்பர்கள்']]),
    note('Plural -ES', 'box → boxes', 'ப்ளூரல் இ-எஸ்', 'பன்மைக்கு -es சேர்த்தல்', 'Nouns ending in s, ss, sh, ch, or x usually take -es.', 'Class note · Plural rule', '📦', [['bus → buses', 'பேருந்து → பேருந்துகள்'], ['box → boxes', 'பெட்டி → பெட்டிகள்'], ['watch → watches', 'கைக்கடிகாரம் → கைக்கடிகாரங்கள்']]),
    note('Plural -IES', 'baby → babies', 'ப்ளூரல் ஐ-ஈ-எஸ்', 'y-ஐ நீக்கி -ies சேர்த்தல்', 'For consonant + y, change y to ies.', 'Class note · Plural rule', '👶', [['baby → babies', 'குழந்தை → குழந்தைகள்'], ['city → cities', 'நகரம் → நகரங்கள்'], ['family → families', 'குடும்பம் → குடும்பங்கள்']]),
    note('Vowel + Y', 'boy → boys', 'வவல் ப்ளஸ் வை', 'உயிரெழுத்து + y என்றால் -s', 'When a vowel comes before y, keep the y and add -s.', 'Class note · Plural rule', '🧸', [['boy → boys', 'சிறுவன் → சிறுவர்கள்'], ['toy → toys', 'பொம்மை → பொம்மைகள்'], ['key → keys', 'சாவி → சாவிகள்']]),
    note('Plural -VES', 'knife → knives', 'ப்ளூரல் வி-ஈ-எஸ்', 'f / fe-ஐ -ves ஆக மாற்றுதல்', 'Some nouns ending in f or fe change to ves.', 'Class note · Plural rule', '🍃', [['leaf → leaves', 'இலை → இலைகள்'], ['knife → knives', 'கத்தி → கத்திகள்'], ['wife → wives', 'மனைவி → மனைவிகள்']]),
    note('F Exceptions', 'roof → roofs', 'எஃப் எக்ஸெப்ஷன்ஸ்', 'f விதிவிலக்குகள்', 'Some words ending in f simply add -s.', 'Class note · Exception', '🏠', [['roof → roofs', 'கூரை → கூரைகள்'], ['chef → chefs', 'சமையல்காரர் → சமையல்காரர்கள்'], ['chief → chiefs', 'தலைவர் → தலைவர்கள்']]),
    note('Irregular Plurals', 'child → children', 'இரெக்யுலர் ப்ளூரல்ஸ்', 'விதிவிலக்கான பன்மைச் சொற்கள்', 'These plurals change form instead of following a regular ending.', 'Class note · Irregular plural', '🦷', [['man → men', 'ஆண் → ஆண்கள்'], ['child → children', 'குழந்தை → குழந்தைகள்'], ['tooth → teeth', 'பல் → பற்கள்']]),
    note('Same Plural', 'sheep → sheep', 'சேம் ப்ளூரல்', 'மாறாத பன்மை வடிவம்', 'Some nouns have the same singular and plural form.', 'Class note · Irregular plural', '🐑', [['one sheep → many sheep', 'ஒரு செம்மறியாடு → பல செம்மறியாடுகள்'], ['one deer → many deer', 'ஒரு மான் → பல மான்கள்'], ['one fish → many fish', 'ஒரு மீன் → பல மீன்கள்']]),
  ]},
  { id: 'class-grammar', section: 'class-notes' as const, name: 'Parts of Speech', tamil: 'சொல் வகைகள்', emoji: '📝', color: '#6576a8', words: [
    note('Noun', 'Noun', 'நவுன்', 'பெயர்ச்சொல்', 'A naming word for a person, place, thing, or idea.', 'Part of speech', '🏷️', [['Ravi is a student.', 'ரவி ஒரு மாணவர்.'], ['This is a book.', 'இது ஒரு புத்தகம்.'], ['Chennai is a city.', 'சென்னை ஒரு நகரம்.']]),
    note('Pronoun', 'Pro-noun', 'ப்ரோ-நவுன்', 'பிரதிப்பெயர்', 'A word used instead of a noun.', 'Part of speech', '👤', [['Ravi is here. He is ready.', 'ரவி இங்கே இருக்கிறார். அவர் தயாராக இருக்கிறார்.'], ['The books are new. They are mine.', 'புத்தகங்கள் புதியவை. அவை என்னுடையவை.'], ['Annie was late because she missed the bus.', 'பேருந்தைத் தவறவிட்டதால் ஆனி தாமதமாக வந்தாள்.']]),
    note('Adjective', 'Ad-jec-tive', 'அட்-ஜெக்-டிவ்', 'பெயரடை', 'A word that describes a noun or pronoun.', 'Part of speech', '🎨', [['She has a beautiful dress.', 'அவரிடம் அழகான உடை உள்ளது.'], ['I have a small bag.', 'என்னிடம் ஒரு சிறிய பை உள்ளது.'], ['The sky is blue.', 'வானம் நீலமாக உள்ளது.']]),
    note('Verb', 'Verb', 'வெர்ப்', 'வினைச்சொல்', 'A word that shows an action or state.', 'Part of speech', '🏃', [['The boy runs.', 'சிறுவன் ஓடுகிறான்.'], ['You write neatly.', 'நீங்கள் அழகாக எழுதுகிறீர்கள்.'], ['She is happy.', 'அவர் மகிழ்ச்சியாக இருக்கிறார்.']]),
    note('Adverb', 'Ad-verb', 'அட்-வெர்ப்', 'வினையடை', 'A word that describes a verb, adjective, or another adverb.', 'Part of speech', '⚡', [['The boy runs quickly.', 'சிறுவன் வேகமாக ஓடுகிறான்.'], ['Please speak slowly.', 'தயவுசெய்து மெதுவாகப் பேசுங்கள்.'], ['She writes very neatly.', 'அவர் மிகவும் அழகாக எழுதுகிறார்.']]),
    note('Conjunction', 'Con-junc-tion', 'கன்-ஜங்-ஷன்', 'இணைப்புச்சொல்', 'A word that joins words or sentences.', 'Part of speech', '🔗', [['I like tea and coffee.', 'எனக்கு தேநீரும் காபியும் பிடிக்கும்.'], ['She is tired but happy.', 'அவர் சோர்வாக இருந்தாலும் மகிழ்ச்சியாக இருக்கிறார்.'], ['Come now or call later.', 'இப்போது வாருங்கள் அல்லது பிறகு அழையுங்கள்.']]),
    note('Preposition', 'Prep-o-si-tion', 'ப்ரெப்-அ-ஸி-ஷன்', 'இடைச்சொல்', 'A word that shows place, time, or position.', 'Part of speech', '📍', [['The book is on the table.', 'புத்தகம் மேசையின் மேல் உள்ளது.'], ['The cat is under the chair.', 'பூனை நாற்காலியின் கீழ் உள்ளது.'], ['I wake up at six.', 'நான் ஆறு மணிக்கு எழுந்திருப்பேன்.']]),
    note('Interjection', 'In-ter-jec-tion', 'இன்-டர்-ஜெக்-ஷன்', 'உணர்ச்சிச் சொல்', 'A short word that shows a sudden feeling.', 'Part of speech', '❗', [['Wow! This is beautiful.', 'ஆஹா! இது அழகாக இருக்கிறது.'], ['Oh! I forgot my bag.', 'ஓ! நான் என் பையை மறந்துவிட்டேன்.'], ['Hurray! We won.', 'ஹுரே! நாம் வென்றோம்.']]),
  ]},
  { id: 'class-nouns', section: 'class-notes' as const, name: 'Types of Nouns', tamil: 'பெயர்ச்சொல் வகைகள்', emoji: '🏷️', color: '#9a6d4f', words: [
    note('Proper Noun', 'Prop-er Noun', 'ப்ராப்பர் நவுன்', 'சிறப்புப் பெயர்', 'The special name of a particular person, place, or thing; it begins with a capital letter.', 'Type of noun', '🔠', [['Pratap is my friend.', 'பிரதாப் என் நண்பர்.'], ['Italy is a country.', 'இத்தாலி ஒரு நாடு.'], ['Monday is a busy day.', 'திங்கட்கிழமை பரபரப்பான நாள்.']]),
    note('Common Noun', 'Com-mon Noun', 'காமன் நவுன்', 'பொதுப்பெயர்', 'A general name for a person, place, or thing.', 'Type of noun', '🏘️', [['The girl is reading.', 'சிறுமி படித்துக்கொண்டிருக்கிறாள்.'], ['This town is clean.', 'இந்த நகரம் சுத்தமாக உள்ளது.'], ['I like this fruit.', 'எனக்கு இந்தப் பழம் பிடிக்கும்.']]),
    note('Abstract Noun', 'Ab-stract Noun', 'அப்ஸ்ட்ராக்ட் நவுன்', 'கருத்துப் பெயர்', 'The name of a feeling, quality, idea, or state that cannot be touched.', 'Type of noun', '💭', [['Love gives us strength.', 'அன்பு நமக்கு வலிமை தருகிறது.'], ['Honesty is important.', 'நேர்மை முக்கியமானது.'], ['Happiness is a good feeling.', 'மகிழ்ச்சி ஒரு நல்ல உணர்வு.']]),
    note('Collective Noun', 'Col-lec-tive Noun', 'கலெக்டிவ் நவுன்', 'கூட்டுப் பெயர்', 'A word used to name a group of people, animals, or things.', 'Type of noun', '🐝', [['a swarm of bees', 'தேனீக்களின் கூட்டம்'], ['a flock of birds', 'பறவைகளின் கூட்டம்'], ['a bunch of grapes', 'திராட்சைக் கொத்து']]),
    note('Countable Noun', 'Count-a-ble Noun', 'கவுன்டபிள் நவுன்', 'எண்ணக்கூடிய பெயர்ச்சொல்', 'A thing we can count; it has singular and plural forms.', 'Type of noun', '🔢', [['one book, two books', 'ஒரு புத்தகம், இரண்டு புத்தகங்கள்'], ['a doctor, three doctors', 'ஒரு மருத்துவர், மூன்று மருத்துவர்கள்'], ['How many apples?', 'எத்தனை ஆப்பிள்கள்?']]),
    note('Uncountable Noun', 'Un-count-a-ble Noun', 'அன்கவுன்டபிள் நவுன்', 'எண்ணமுடியாத பெயர்ச்சொல்', 'A substance or idea we usually see as a whole and do not count separately.', 'Type of noun', '💧', [['I need some water.', 'எனக்கு கொஞ்சம் தண்ணீர் வேண்டும்.'], ['Music makes me happy.', 'இசை என்னை மகிழ்ச்சிப்படுத்துகிறது.'], ['This information is useful.', 'இந்தத் தகவல் பயனுள்ளதாக உள்ளது.']]),
  ]},
  { id: 'class-gender', section: 'class-notes' as const, name: 'Gender Word Pairs', tamil: 'ஆண்–பெண் சொல் இணைகள்', emoji: '👨‍👩‍👧', color: '#aa6b87', words: [
    note('Father / Mother', 'Fa-ther · Moth-er', 'ஃபாதர் · மதர்', 'அப்பா / அம்மா', 'The male parent and the female parent.', 'Masculine · Feminine', '👨‍👩‍👧', [['My father is a teacher.', 'என் அப்பா ஒரு ஆசிரியர்.'], ['My mother is a teacher.', 'என் அம்மா ஒரு ஆசிரியர்.'], ['They are my father and mother.', 'அவர்கள் என் அப்பாவும் அம்மாவும்.']]),
    note('Son / Daughter', 'Son · Daugh-ter', 'சன் · டாட்டர்', 'மகன் / மகள்', 'A male child and a female child.', 'Masculine · Feminine', '👦👧', [['Their son is a student.', 'அவர்களின் மகன் ஒரு மாணவர்.'], ['Their daughter is a doctor.', 'அவர்களின் மகள் ஒரு மருத்துவர்.'], ['They have a son and a daughter.', 'அவர்களுக்கு ஒரு மகனும் ஒரு மகளும் உள்ளனர்.']]),
    note('Brother / Sister', 'Broth-er · Sis-ter', 'பிரதர் · சிஸ்டர்', 'சகோதரன் / சகோதரி', 'A male sibling and a female sibling.', 'Masculine · Feminine', '🧑‍🤝‍🧑', [['He is my brother.', 'அவர் என் சகோதரர்.'], ['She is my sister.', 'அவர் என் சகோதரி.'], ['My brother and sister are kind.', 'என் சகோதரரும் சகோதரியும் அன்பானவர்கள்.']]),
    note('Man / Woman', 'Man · Wom-an', 'மேன் · வுமன்', 'ஆண் / பெண்', 'An adult male person and an adult female person.', 'Masculine · Feminine', '👨👩', [['The man is tall.', 'அந்த ஆண் உயரமானவர்.'], ['The woman is happy.', 'அந்த பெண் மகிழ்ச்சியாக இருக்கிறார்.'], ['The man and woman are teachers.', 'அந்த ஆணும் பெண்ணும் ஆசிரியர்கள்.']]),
    note('King / Queen', 'King · Queen', 'கிங் · க்வீன்', 'அரசன் / அரசி', 'A male ruler and a female ruler.', 'Masculine · Feminine', '🤴👸', [['The king is kind.', 'அரசர் அன்பானவர்.'], ['The queen is beautiful.', 'அரசி அழகானவர்.'], ['The king and queen live in a palace.', 'அரசரும் அரசியும் அரண்மனையில் வசிக்கிறார்கள்.']]),
    note('Uncle / Aunt', 'Un-cle · Aunt', 'அங்கிள் · ஆன்ட்', 'மாமா / அத்தை', 'A male relative and a female relative of your parents’ generation.', 'Masculine · Feminine', '🧔👩', [['My uncle is at home.', 'என் மாமா வீட்டில் இருக்கிறார்.'], ['My aunt is at home.', 'என் அத்தை வீட்டில் இருக்கிறார்.'], ['My uncle and aunt are helpful.', 'என் மாமாவும் அத்தையும் உதவிகரமானவர்கள்.']]),
  ]},
  { id: 'class-adjectives', section: 'class-notes' as const, name: 'Adjectives & Comparison', tamil: 'பெயரடைகளும் ஒப்பீடும்', emoji: '📏', color: '#4e927f', words: [
    note('Big', 'Big', 'பிக்', 'பெரிய', 'Large in size.', 'Adjective', '🐘', [['The jungle is very big.', 'காடு மிகவும் பெரியது.'], ['It is a big box.', 'அது ஒரு பெரிய பெட்டி.'], ['We saw a big building.', 'நாங்கள் ஒரு பெரிய கட்டிடத்தைப் பார்த்தோம்.']]),
    note('Small', 'Small', 'ஸ்மால்', 'சிறிய', 'Little in size.', 'Adjective', '🐭', [['I have a small bag.', 'என்னிடம் ஒரு சிறிய பை உள்ளது.'], ['The mouse is small.', 'எலி சிறியது.'], ['This is a small town.', 'இது ஒரு சிறிய நகரம்.']]),
    note('Kind', 'Kind', 'கைண்ட்', 'அன்பான', 'Caring and helpful to other people.', 'Adjective', '💛', [['He is a kind man.', 'அவர் ஒரு அன்பான மனிதர்.'], ['My teacher is kind.', 'என் ஆசிரியர் அன்பானவர்.'], ['Be kind to others.', 'மற்றவர்களிடம் அன்பாக இருங்கள்.']]),
    note('Brave', 'Brave', 'ப்ரேவ்', 'துணிச்சலான', 'Showing courage and not being afraid.', 'Adjective', '🦸', [['The girl is brave.', 'அந்த சிறுமி துணிச்சலானவள்.'], ['Be brave and try again.', 'துணிச்சலாக இருந்து மீண்டும் முயற்சி செய்யுங்கள்.'], ['The brave boy helped his friend.', 'துணிச்சலான சிறுவன் தனது நண்பருக்கு உதவினான்.']]),
    note('Longer', 'long → longer → longest', 'லாங் · லாங்கர் · லாங்கஸ்ட்', 'நீளம் → இன்னும் நீளம் → மிக நீளம்', 'Long is positive, longer compares two, and longest compares three or more.', 'Degrees of comparison', '📏', [['This is a long rope.', 'இது ஒரு நீளமான கயிறு.'], ['This rope is longer than that rope.', 'இந்தக் கயிறு அந்தக் கயிறைவிட நீளமானது.'], ['This is the longest rope.', 'இதுதான் மிக நீளமான கயிறு.']]),
    note('Hotter', 'hot → hotter → hottest', 'ஹாட் · ஹாட்டர் · ஹாட்டஸ்ட்', 'சூடு → அதிக சூடு → மிக அதிக சூடு', 'Hot is positive, hotter compares two, and hottest compares three or more.', 'Degrees of comparison', '🔥', [['The tea is hot.', 'தேநீர் சூடாக உள்ளது.'], ['Today is hotter than yesterday.', 'இன்று நேற்றைவிட சூடாக உள்ளது.'], ['July is the hottest month.', 'ஜூலை மிகவும் சூடான மாதம்.']]),
    note('Healthier', 'healthy → healthier → healthiest', 'ஹெல்தி · ஹெல்தியர் · ஹெல்தியஸ்ட்', 'ஆரோக்கியமான → மேலும் ஆரோக்கியமான → மிக ஆரோக்கியமான', 'These three forms compare how healthy people or things are.', 'Degrees of comparison', '🥗', [['This food is healthy.', 'இந்த உணவு ஆரோக்கியமானது.'], ['Fruit is healthier than sweets.', 'இனிப்புகளைவிட பழம் ஆரோக்கியமானது.'], ['Walking is one of the healthiest habits.', 'நடப்பது மிகவும் ஆரோக்கியமான பழக்கங்களில் ஒன்று.']]),
  ]},
  { id: 'class-speaking', section: 'class-notes' as const, name: 'Daily Speaking Notes', tamil: 'அன்றாடப் பேச்சுக் குறிப்புகள்', emoji: '🗣️', color: '#4c8797', words: [
    note('Time', 'Time', 'டைம்', 'நேரம்', 'The measured part of a day shown by a clock.', 'Class vocabulary', '🕐', [['What time are you coming?', 'நீங்கள் எத்தனை மணிக்கு வருகிறீர்கள்?'], ['I wake up at six o’clock.', 'நான் ஆறு மணிக்கு எழுந்திருப்பேன்.'], ['It is time for class.', 'இது வகுப்பிற்கான நேரம்.']]),
    note('Jungle', 'Jun-gle', 'ஜங்கல்', 'காடு', 'A thick forest where many wild animals and plants live.', 'Story vocabulary', '🌴', [['The jungle is very big.', 'காடு மிகவும் பெரியது.'], ['A lion lives in the jungle.', 'ஒரு சிங்கம் காட்டில் வாழ்கிறது.'], ['The hare lived near a jungle.', 'முயல் ஒரு காட்டின் அருகில் வாழ்ந்தது.']]),
    note('Town', 'Town', 'டவுன்', 'நகரம் / ஊர்', 'A place where people live that is smaller than a city.', 'Story vocabulary', '🏘️', [['My town is very neat.', 'என் ஊர் மிகவும் சுத்தமாக உள்ளது.'], ['This is a small town.', 'இது ஒரு சிறிய நகரம்.'], ['Many people live in the town.', 'பலர் அந்த நகரத்தில் வசிக்கிறார்கள்.']]),
    note('Raw Mango', 'Raw Man-go', 'ரா மேங்கோ', 'மாங்காய்', 'A mango that is not ripe yet; it usually tastes sour.', 'Class vocabulary · Food', '🥭', [['Raw mango is sour.', 'மாங்காய் புளிப்பாக இருக்கும்.'], ['We prepare curries with raw mango.', 'நாங்கள் மாங்காயைப் பயன்படுத்தி குழம்புகள் செய்கிறோம்.'], ['Raw mango is used in pickles.', 'மாங்காய் ஊறுகாயில் பயன்படுத்தப்படுகிறது.']]),
    note('Creeper', 'Creep-er', 'க்ரீப்பர்', 'படர்கொடி', 'A plant that grows along the ground or climbs with support.', 'Class vocabulary · Plant', '🌿', [['The pumpkin plant is a creeper.', 'பூசணிச் செடி ஒரு படர்கொடி.'], ['The creeper grows along the wall.', 'படர்கொடி சுவரின் ஓரமாக வளர்கிறது.'], ['This creeper has green leaves.', 'இந்தப் படர்கொடியில் பச்சை இலைகள் உள்ளன.']]),
    note('Home Maker', 'Home Mak-er', 'ஹோம் மேக்கர்', 'இல்லத்தரசி / வீட்டைப் பராமரிப்பவர்', 'A person whose main work is caring for the home and family.', 'Class vocabulary · Occupation', '🏡', [['My mother is a home maker.', 'என் அம்மா வீட்டைப் பராமரிப்பவர்.'], ['A home maker manages the home.', 'வீட்டைப் பராமரிப்பவர் வீட்டை நிர்வகிக்கிறார்.'], ['She is a busy home maker.', 'அவர் பரபரப்பாக இயங்கும் இல்லத்தரசி.']]),
    note('Introduce Yourself', 'In-tro-duce Your-self', 'இன்ட்ரட்யூஸ் யுவர்செல்ஃப்', 'உங்களை அறிமுகப்படுத்துங்கள்', 'Tell someone your name and a few simple facts about yourself.', 'Speaking practice', '🙋', [['What is your name? My name is Anu.', 'உங்கள் பெயர் என்ன? என் பெயர் அனு.'], ['What do you do? I am a student.', 'நீங்கள் என்ன செய்கிறீர்கள்? நான் ஒரு மாணவர்.'], ['Where do you live? I live in Bengaluru.', 'நீங்கள் எங்கே வசிக்கிறீர்கள்? நான் பெங்களூரில் வசிக்கிறேன்.']]),
    note('Daily Routine', 'Dai-ly Rou-tine', 'டெய்லி ரூட்டீன்', 'தினசரி வழக்கம்', 'The actions you usually do every day.', 'Speaking practice', '📅', [['I wake up at six every morning.', 'நான் தினமும் காலை ஆறு மணிக்கு எழுந்திருப்பேன்.'], ['I go to school at eight.', 'நான் எட்டு மணிக்கு பள்ளிக்குச் செல்வேன்.'], ['I go to bed at ten.', 'நான் பத்து மணிக்கு தூங்கச் செல்வேன்.']]),
    note('Favourite Place', 'Fa-vour-ite Place', 'ஃபேவரிட் ப்ளேஸ்', 'பிடித்த இடம்', 'A place you like more than other places.', 'Writing and speaking prompt', '🌄', [['Which is your favourite place?', 'உங்களுக்கு மிகவும் பிடித்த இடம் எது?'], ['Why do you like that place?', 'அந்த இடம் உங்களுக்கு ஏன் பிடிக்கும்?'], ['Who did you visit it with?', 'நீங்கள் யாருடன் அங்கு சென்றீர்கள்?']]),
    note('Favourite Song', 'Fa-vour-ite Song', 'ஃபேவரிட் சாங்', 'பிடித்த பாடல்', 'A song you like more than other songs.', 'Writing and speaking prompt', '🎵', [['Which is your favourite song?', 'உங்களுக்கு மிகவும் பிடித்த பாடல் எது?'], ['Why is it your favourite?', 'அது உங்களுக்கு ஏன் மிகவும் பிடிக்கும்?'], ['Who is the hero in the movie?', 'அந்தத் திரைப்படத்தின் கதாநாயகன் யார்?']]),
  ]},
];
