export type CourseExample = { english: string; tamil: string };

export type IntermediateLesson = {
  day: number;
  title: string;
  tamil: string;
  emoji: string;
  videoId: string;
  explanation: string;
  formula: string;
  examples: CourseExample[];
  remember: string[];
  practice: string;
};

const e = (english: string, tamil: string): CourseExample => ({ english, tamil });

export const intermediateLessons: IntermediateLesson[] = [
  { day: 1, title: 'Be Verbs', tamil: 'Be வினைச்சொற்கள்', emoji: '🌱', videoId: 'fuWfu530W6c', explanation: 'ஒருவர் யார், எப்படி இருக்கிறார், எங்கே இருக்கிறார் என்று சொல்ல am, is, are பயன்படுத்துகிறோம். கடந்த காலத்திற்கு was, were பயன்படுத்தலாம்.', formula: 'I + am · He/She/It + is · You/We/They + are', examples: [e('I am at home.', 'நான் வீட்டில் இருக்கிறேன்.'), e('She is happy.', 'அவள் மகிழ்ச்சியாக இருக்கிறாள்.'), e('They are ready.', 'அவர்கள் தயாராக இருக்கிறார்கள்.')], remember: ['I உடன் எப்போதும் am.', 'ஒருவர்/ஒன்று என்றால் is; பலர்/பல பொருட்கள் என்றால் are.'], practice: 'உங்களைப் பற்றி am பயன்படுத்தி 2 வாக்கியங்களும், குடும்பத்தைப் பற்றி is/are பயன்படுத்தி 3 வாக்கியங்களும் சொல்லுங்கள்.' },
  { day: 2, title: 'Have, Has & Had', tamil: 'Have, Has, Had பயன்பாடு', emoji: '👜', videoId: 'Ex7SaCjzVu4', explanation: 'ஒருவரிடம் ஒன்று இருப்பதை அல்லது ஒரு அனுபவத்தைச் சொல்ல have/has பயன்படும். கடந்த காலத்தில் எல்லோருக்கும் had பயன்படும்.', formula: 'I/You/We/They + have · He/She/It + has · Past: had', examples: [e('I have a question.', 'எனக்கு ஒரு கேள்வி உள்ளது.'), e('She has a new phone.', 'அவளிடம் ஒரு புதிய தொலைபேசி உள்ளது.'), e('We had a good time.', 'நாங்கள் நல்ல நேரத்தை அனுபவித்தோம்.')], remember: ['He, She, It உடன் has.', 'Had என்பது எல்லா subject-களுக்கும் ஒரே மாதிரி.'], practice: 'வீட்டில் உள்ள பொருட்களைப் பற்றி have/has கொண்டு 5 வாக்கியங்கள் சொல்லுங்கள்.' },
  { day: 3, title: 'Sentence Basics', tamil: 'எளிய வாக்கிய அமைப்பு', emoji: '🧱', videoId: 'yKzHTzO7udA', explanation: 'ஒரு எளிய ஆங்கில வாக்கியத்தில் முதலில் யார், அடுத்து என்ன செய்கிறார், கடைசியில் எதை அல்லது எங்கே என்பது வரும்.', formula: 'Subject + Verb + Object / Place', examples: [e('I drink tea.', 'நான் தேநீர் குடிக்கிறேன்.'), e('Mother cooks dinner.', 'அம்மா இரவு உணவு சமைக்கிறார்.'), e('We live in Chennai.', 'நாங்கள் சென்னையில் வசிக்கிறோம்.')], remember: ['தமிழிலிருந்து வார்த்தைக்கு வார்த்தை மாற்ற வேண்டாம்.', 'யார் செய்கிறார் என்பதை முதலில் சொல்லுங்கள்.'], practice: 'I, She, We என்று தொடங்கி உங்கள் அன்றாட வாழ்க்கையைப் பற்றி தலா ஒரு வாக்கியம் சொல்லுங்கள்.' },
  { day: 4, title: 'Introduction to Tenses', tamil: 'காலங்களின் அறிமுகம்', emoji: '🕰️', videoId: '24A2XCcciVs', explanation: 'செயல் எப்போது நடக்கிறது என்பதை tense காட்டுகிறது: நிகழ்காலம், கடந்த காலம், எதிர்காலம். ஒவ்வொன்றிலும் simple, continuous, perfect, perfect continuous என நான்கு வகைகள் உள்ளன.', formula: 'Present · Past · Future × 4 forms = 12 tenses', examples: [e('I cook every day.', 'நான் தினமும் சமைக்கிறேன்.'), e('I cooked yesterday.', 'நான் நேற்று சமைத்தேன்.'), e('I will cook tomorrow.', 'நான் நாளை சமைப்பேன்.')], remember: ['Time word-ஐ முதலில் கவனியுங்கள்.', 'முதலில் simple tenses-ஐ நன்றாகப் பழகுங்கள்.'], practice: 'ஒரே செயலை today, yesterday, tomorrow என்று மாற்றி மூன்று வாக்கியங்களாகச் சொல்லுங்கள்.' },
  { day: 5, title: 'Simple Present Tense', tamil: 'எளிய நிகழ்காலம்', emoji: '☀️', videoId: 'mxzZGpOGE_k', explanation: 'தினசரி பழக்கம், பொதுவான உண்மை, வழக்கமாக நடக்கும் செயல் ஆகியவற்றுக்கு simple present பயன்படுத்துகிறோம்.', formula: 'I/You/We/They + V1 · He/She/It + V1+s/es', examples: [e('I walk every morning.', 'நான் தினமும் காலையில் நடக்கிறேன்.'), e('She drinks coffee.', 'அவள் காபி குடிக்கிறாள்.'), e('The sun rises in the east.', 'சூரியன் கிழக்கில் உதிக்கிறது.')], remember: ['He/She/It என்றால் verb-க்கு s அல்லது es சேர்க்கவும்.', 'every day, usually, always போன்ற சொற்கள் உதவும்.'], practice: 'உங்கள் காலை பழக்கத்தை simple present-ல் 5 வாக்கியங்களாகச் சொல்லுங்கள்.' },
  { day: 6, title: 'Simple Past Tense', tamil: 'எளிய கடந்தகாலம்', emoji: '↩️', videoId: 'p2qgd8PuGZ4', explanation: 'கடந்த காலத்தில் தொடங்கி முடிந்த செயலை simple past-ல் சொல்கிறோம். Regular verb-க்கு -ed வரும்; irregular verb தனியாக மாறும்.', formula: 'Subject + V2 + Object', examples: [e('I called my daughter.', 'நான் என் மகளை அழைத்தேன்.'), e('She went to the shop.', 'அவள் கடைக்குச் சென்றாள்.'), e('We watched a movie.', 'நாங்கள் ஒரு திரைப்படம் பார்த்தோம்.')], remember: ['Positive sentence-ல் V2 பயன்படுத்தவும்.', 'Did வந்தால் main verb மீண்டும் V1 ஆகும்.'], practice: 'நேற்று நீங்கள் செய்த 5 செயல்களை past tense-ல் சொல்லுங்கள்.' },
  { day: 7, title: 'Simple Future Tense', tamil: 'எளிய எதிர்காலம்', emoji: '🔜', videoId: 'HTXXP0lnEFo', explanation: 'பின்னர் நடக்கவிருக்கும் செயல், முடிவு அல்லது வாக்குறுதிக்கு will + V1 பயன்படுத்துகிறோம்.', formula: 'Subject + will + V1', examples: [e('I will call you tonight.', 'நான் இன்று இரவு உங்களை அழைப்பேன்.'), e('She will come tomorrow.', 'அவள் நாளை வருவாள்.'), e('We will help you.', 'நாங்கள் உங்களுக்கு உதவுவோம்.')], remember: ['Will-க்கு அடுத்து எப்போதும் V1.', 'won’t என்பது will not என்பதன் சுருக்கம்.'], practice: 'நாளை செய்யப் போகும் 5 விஷயங்களை will பயன்படுத்திச் சொல்லுங்கள்.' },
  { day: 8, title: 'Present Continuous', tamil: 'நிகழ்கால தொடர்ச்சி', emoji: '▶️', videoId: 'ykI0HP8EKTY', explanation: 'இப்போது நடந்துகொண்டிருக்கும் செயலை present continuous-ல் சொல்கிறோம்.', formula: 'Subject + am/is/are + V-ing', examples: [e('I am cooking now.', 'நான் இப்போது சமைத்துக்கொண்டிருக்கிறேன்.'), e('He is sleeping.', 'அவர் தூங்கிக்கொண்டிருக்கிறார்.'), e('They are talking.', 'அவர்கள் பேசிக்கொண்டிருக்கிறார்கள்.')], remember: ['am/is/are இல்லாமல் V-ing மட்டும் பயன்படுத்த வேண்டாம்.', 'now, at the moment போன்ற சொற்கள் குறியீடுகள்.'], practice: 'உங்கள் அருகில் இப்போது நடக்கும் 5 செயல்களைப் பார்த்துச் சொல்லுங்கள்.' },
  { day: 9, title: 'Past Continuous', tamil: 'கடந்தகால தொடர்ச்சி', emoji: '🎞️', videoId: 'cIJ1h6cFzmE', explanation: 'கடந்த காலத்தில் ஒரு குறிப்பிட்ட நேரத்தில் நடந்துகொண்டிருந்த செயலை past continuous-ல் சொல்கிறோம்.', formula: 'I/He/She/It + was + V-ing · You/We/They + were + V-ing', examples: [e('I was cooking at seven.', 'நான் ஏழு மணிக்கு சமைத்துக்கொண்டிருந்தேன்.'), e('They were waiting for the bus.', 'அவர்கள் பேருந்துக்காகக் காத்துக்கொண்டிருந்தார்கள்.'), e('She was sleeping when I called.', 'நான் அழைத்தபோது அவள் தூங்கிக்கொண்டிருந்தாள்.')], remember: ['ஒருவர் என்றால் was; பலர் என்றால் were.', 'when வந்தால் குறுகிய செயல் பல நேரங்களில் simple past-ல் வரும்.'], practice: 'நேற்று காலை 8 மணி, மதியம் 1 மணி, இரவு 8 மணிக்கு என்ன செய்துகொண்டிருந்தீர்கள் என்று சொல்லுங்கள்.' },
  { day: 10, title: 'Future Continuous', tamil: 'எதிர்கால தொடர்ச்சி', emoji: '⏩', videoId: 'MCn6MH_1dIg', explanation: 'எதிர்காலத்தில் ஒரு குறிப்பிட்ட நேரத்தில் நடந்துகொண்டிருக்கும் செயலை future continuous-ல் சொல்கிறோம்.', formula: 'Subject + will be + V-ing', examples: [e('I will be travelling tomorrow.', 'நான் நாளை பயணம் செய்துகொண்டிருப்பேன்.'), e('She will be working at ten.', 'அவள் பத்து மணிக்கு வேலை செய்துகொண்டிருப்பாள்.'), e('We will be waiting for you.', 'நாங்கள் உங்களுக்காகக் காத்துக்கொண்டிருப்போம்.')], remember: ['எல்லா subject-க்கும் will be ஒரே மாதிரி.', 'குறிப்பிட்ட future time-ஐ சேர்த்தால் பொருள் தெளிவாகும்.'], practice: 'நாளை மூன்று வெவ்வேறு நேரங்களில் நீங்கள் என்ன செய்துகொண்டிருப்பீர்கள் என்று சொல்லுங்கள்.' },
  { day: 11, title: 'Present Perfect', tamil: 'நிகழ்கால நிறைவு', emoji: '✅', videoId: '-2GsJRk23XU', explanation: 'கடந்த காலத்தில் முடிந்து அதன் விளைவு இப்போது இருக்கும் செயல் அல்லது வாழ்க்கை அனுபவத்திற்கு present perfect பயன்படும்.', formula: 'I/You/We/They + have + V3 · He/She/It + has + V3', examples: [e('I have finished my work.', 'நான் என் வேலையை முடித்துவிட்டேன்.'), e('She has gone to the shop.', 'அவள் கடைக்குச் சென்றுவிட்டாள்.'), e('We have seen this movie.', 'நாங்கள் இந்தப் படத்தைப் பார்த்திருக்கிறோம்.')], remember: ['have/has-க்கு அடுத்து V3.', 'yesterday போன்ற முடிந்த நேரத்துடன் இதைப் பயன்படுத்த வேண்டாம்.'], practice: 'இன்று நீங்கள் முடித்த மூன்று வேலைகளை already அல்லது just சேர்த்துச் சொல்லுங்கள்.' },
  { day: 12, title: 'Past Perfect', tamil: 'கடந்தகால நிறைவு', emoji: '⏮️', videoId: 'v5DPShi4Pvo', explanation: 'கடந்த காலத்தில் இரண்டு செயல்கள் நடந்தால், முதலில் முடிந்த செயலை past perfect-ல் சொல்கிறோம்.', formula: 'Subject + had + V3', examples: [e('I had eaten before she came.', 'அவள் வருவதற்கு முன் நான் சாப்பிட்டிருந்தேன்.'), e('The bus had left when we arrived.', 'நாங்கள் வந்தபோது பேருந்து சென்றிருந்தது.'), e('She had finished the work.', 'அவள் வேலையை முடித்திருந்தாள்.')], remember: ['முதலில் நடந்த செயல்: had + V3.', 'அடுத்த செயல் பெரும்பாலும் simple past.'], practice: '“Before…” அல்லது “When…” கொண்டு கடந்த காலத்தின் இரண்டு செயல்களை இணைத்து 3 வாக்கியங்கள் சொல்லுங்கள்.' },
  { day: 13, title: 'Future Perfect', tamil: 'எதிர்கால நிறைவு', emoji: '🏁', videoId: 'fqB1Scn5NV0', explanation: 'எதிர்காலத்தில் ஒரு குறிப்பிட்ட நேரத்திற்குள் முடிந்திருக்கும் செயலை future perfect-ல் சொல்கிறோம்.', formula: 'Subject + will have + V3', examples: [e('I will have finished by six.', 'நான் ஆறு மணிக்குள் முடித்திருப்பேன்.'), e('She will have reached home by then.', 'அதற்குள் அவள் வீட்டை அடைந்திருப்பாள்.'), e('We will have completed the course.', 'நாங்கள் பாடத்திட்டத்தை முடித்திருப்போம்.')], remember: ['will have-க்கு அடுத்து V3.', 'by, by then, by tomorrow போன்றவை பொதுவாக வரும்.'], practice: 'இந்த வார முடிவிற்குள் நீங்கள் முடித்திருக்கும் 3 வேலைகளைச் சொல்லுங்கள்.' },
  { day: 14, title: 'Present Perfect Continuous', tamil: 'நிகழ்கால நிறைவுத் தொடர்ச்சி', emoji: '🌊', videoId: 'Zm2wLOdTZEY', explanation: 'கடந்த காலத்தில் தொடங்கி இப்போது வரை தொடரும் செயலை present perfect continuous-ல் சொல்கிறோம்.', formula: 'Subject + have/has been + V-ing + since/for', examples: [e('I have been waiting for an hour.', 'நான் ஒரு மணி நேரமாகக் காத்துக்கொண்டிருக்கிறேன்.'), e('She has been living here since 2020.', 'அவள் 2020 முதல் இங்கே வசித்து வருகிறாள்.'), e('It has been raining since morning.', 'காலையிலிருந்து மழை பெய்துகொண்டிருக்கிறது.')], remember: ['Since = தொடங்கிய நேரம்; For = கால அளவு.', 'He/She/It உடன் has been.'], practice: 'நீங்கள் எவ்வளவு காலமாகச் செய்யும் மூன்று விஷயங்களை since/for கொண்டு சொல்லுங்கள்.' },
  { day: 15, title: 'Past Perfect Continuous', tamil: 'கடந்தகால நிறைவுத் தொடர்ச்சி', emoji: '⌛', videoId: 'oRaqYpsBZkA', explanation: 'கடந்த காலத்தில் மற்றொரு நிகழ்வுக்கு முன்பு ஒரு செயல் எவ்வளவு நேரமாகத் தொடர்ந்தது என்பதைச் சொல்கிறது.', formula: 'Subject + had been + V-ing + since/for', examples: [e('I had been waiting for an hour.', 'நான் ஒரு மணி நேரமாகக் காத்துக்கொண்டிருந்தேன்.'), e('She had been cooking before we arrived.', 'நாங்கள் வருவதற்கு முன் அவள் சமைத்துக்கொண்டிருந்தாள்.'), e('They had been travelling all day.', 'அவர்கள் நாள் முழுவதும் பயணம் செய்துகொண்டிருந்தார்கள்.')], remember: ['எல்லா subject-க்கும் had been.', 'கால அளவைச் சேர்ப்பது அர்த்தத்தைத் தெளிவாக்கும்.'], practice: 'ஒரு கடந்த நிகழ்வுக்கு முன் நடந்துகொண்டிருந்த செயல்களைப் பற்றி 3 வாக்கியங்கள் சொல்லுங்கள்.' },
  { day: 16, title: 'Future Perfect Continuous', tamil: 'எதிர்கால நிறைவுத் தொடர்ச்சி', emoji: '📅', videoId: 't_4o2dTK4ZM', explanation: 'எதிர்காலத்தில் ஒரு நேரம் வரும்போது, ஒரு செயல் எவ்வளவு காலமாகத் தொடர்ந்து கொண்டிருக்கும் என்பதைச் சொல்கிறது.', formula: 'Subject + will have been + V-ing + for/since', examples: [e('By June, I will have been living here for a year.', 'ஜூன் மாதத்திற்குள் நான் இங்கே ஒரு வருடமாக வசித்து வருவேன்.'), e('She will have been working for five hours.', 'அவள் ஐந்து மணி நேரமாக வேலை செய்துகொண்டிருப்பாள்.'), e('They will have been travelling all day.', 'அவர்கள் நாள் முழுவதும் பயணம் செய்துகொண்டிருப்பார்கள்.')], remember: ['by + future time பெரும்பாலும் வரும்.', 'will have been எல்லா subject-க்கும் ஒரே மாதிரி.'], practice: 'அடுத்த ஆண்டு வரும்போது நீங்கள் எவ்வளவு காலமாகச் செய்யும் விஷயங்களைப் பற்றி 2 வாக்கியங்கள் சொல்லுங்கள்.' },
  { day: 17, title: '12 Tenses Review', tamil: '12 காலங்கள் மறுபயிற்சி', emoji: '🔄', videoId: 'HNj0Gg_wEsI', explanation: '12 tenses-ஐ ஒரே செயலை வைத்து ஒப்பிட்டால் வேறுபாடு எளிதாகப் புரியும். நேரம் மற்றும் செயல் முடிந்ததா/தொடர்கிறதா என்பதை முதலில் கண்டுபிடியுங்கள்.', formula: 'Simple · Continuous · Perfect · Perfect Continuous', examples: [e('I cook every day.', 'நான் தினமும் சமைக்கிறேன்.'), e('I am cooking now.', 'நான் இப்போது சமைத்துக்கொண்டிருக்கிறேன்.'), e('I have cooked already.', 'நான் ஏற்கனவே சமைத்துவிட்டேன்.')], remember: ['முதலில் present, past, future-ஐ கண்டறியுங்கள்.', 'பிறகு செயல் simple/continuous/perfect என்பதைத் தேர்ந்தெடுங்கள்.'], practice: '“cook” அல்லது “walk” என்ற ஒரு verb-ஐத் தேர்ந்து 12 tenses-லும் சொல்ல முயற்சி செய்யுங்கள்.' },
  { day: 18, title: 'Prepositions – Place', tamil: 'இடத்தைக் காட்டும் சொற்கள்', emoji: '📍', videoId: 'R1xr3zR9Rdc', explanation: 'ஒருவர் அல்லது பொருள் எங்கே இருக்கிறது என்பதை in, on, at, under, near, behind போன்ற prepositions காட்டுகின்றன.', formula: 'Subject + be verb + preposition + place', examples: [e('The keys are on the table.', 'சாவிகள் மேசையின் மேல் உள்ளன.'), e('The bag is under the chair.', 'பை நாற்காலியின் கீழ் உள்ளது.'), e('She is at the hospital.', 'அவள் மருத்துவமனையில் இருக்கிறாள்.')], remember: ['in = உள்ளே; on = மேல் தொடும்படி; at = குறிப்பிட்ட இடம்.', 'படத்தைப் பார்த்துப் பயிற்சி செய்தால் எளிதில் நினைவிருக்கும்.'], practice: 'அறையில் உள்ள 5 பொருட்கள் எங்கே உள்ளன என்று in/on/under/near கொண்டு சொல்லுங்கள்.' },
  { day: 19, title: 'Prepositions – Time & Movement', tamil: 'நேரம் மற்றும் இயக்கச் சொற்கள்', emoji: '🧭', videoId: 'cR0RDc891-4', explanation: 'நேரத்திற்கு at, on, in பயன்படும். இயக்கத்தை to, from, into, through போன்ற சொற்கள் காட்டுகின்றன.', formula: 'at + time · on + day/date · in + month/year/part of day', examples: [e('I wake up at six.', 'நான் ஆறு மணிக்கு விழிக்கிறேன்.'), e('We will meet on Monday.', 'நாம் திங்கட்கிழமை சந்திப்போம்.'), e('She walked into the room.', 'அவள் அறைக்குள் நடந்துசென்றாள்.')], remember: ['கடிகார நேரம் = at; நாள்/தேதி = on; மாதம்/வருடம் = in.', 'go home என்பதில் to வராது.'], practice: 'உங்கள் வாரத் திட்டத்தை at, on, in பயன்படுத்தி 5 வாக்கியங்களாகச் சொல்லுங்கள்.' },
  { day: 20, title: 'Modal Verbs', tamil: 'Modal வினைச்சொற்கள்', emoji: '🧰', videoId: 'wK3VYyk-cIs', explanation: 'can, could, may, might, must, should போன்ற modal verbs திறன், அனுமதி, வாய்ப்பு, ஆலோசனை, கட்டாயம் ஆகியவற்றைக் காட்டுகின்றன.', formula: 'Subject + modal + V1', examples: [e('I can speak Tamil.', 'என்னால் தமிழ் பேச முடியும்.'), e('You should rest.', 'நீங்கள் ஓய்வெடுக்க வேண்டும்.'), e('It might rain.', 'மழை பெய்ய வாய்ப்பு உள்ளது.')], remember: ['Modal-க்கு அடுத்து V1 மட்டும்.', 'He/She என்றாலும் modal மாறாது; verb-க்கு s வராது.'], practice: 'can, should, must பயன்படுத்தி தலா ஒரு வாக்கியம் சொல்லுங்கள்.' },
  { day: 21, title: 'Could', tamil: 'Could பயன்பாடு', emoji: '🙏', videoId: '_mEoAoAXrh0', explanation: 'கடந்தகால திறன், மரியாதையான வேண்டுகோள், ஒரு வாய்ப்பு ஆகியவற்றுக்கு could பயன்படும்.', formula: 'Subject + could + V1 · Could you + V1?', examples: [e('I could swim when I was young.', 'நான் இளமையில் நீந்த முடிந்தது.'), e('Could you help me?', 'நீங்கள் எனக்கு உதவ முடியுமா?'), e('It could be true.', 'அது உண்மையாக இருக்க வாய்ப்பு உள்ளது.')], remember: ['Could you…? என்பது Can you…? விட மரியாதையானது.', 'Could-க்கு அடுத்து V1.'], practice: 'வீட்டில் உதவி கேட்க Could you…? கொண்டு 3 கேள்விகள் சொல்லுங்கள்.' },
  { day: 22, title: 'Will & Would', tamil: 'Will மற்றும் Would', emoji: '💭', videoId: '7qo5Oz5O2Uw', explanation: 'Will எதிர்கால முடிவு அல்லது வாக்குறுதியைக் காட்டும். Would மரியாதையான விருப்பம், வேண்டுகோள் அல்லது கற்பனை நிலையைச் சொல்கிறது.', formula: 'will/would + V1 · would like + noun/to + V1', examples: [e('I will call you tomorrow.', 'நான் நாளை உங்களை அழைப்பேன்.'), e('I would like some tea.', 'எனக்கு கொஞ்சம் தேநீர் வேண்டும்.'), e('Would you open the door?', 'நீங்கள் கதவைத் திறப்பீர்களா?')], remember: ['கடையில் கேட்க “I would like…” மிகவும் பயனுள்ளது.', 'will/would-க்கு அடுத்து V1.'], practice: 'ஒரு உணவகத்தில் ஆர்டர் செய்வது போல would like கொண்டு 3 வாக்கியங்கள் சொல்லுங்கள்.' },
  { day: 23, title: 'Shall & Should', tamil: 'Shall மற்றும் Should', emoji: '💡', videoId: 'vMUt0YHLB2w', explanation: 'Shall I/We என்பது ஆலோசனை அல்லது உதவி முன்வைக்கப் பயன்படும். Should நல்லது, கடமை, ஆலோசனை ஆகியவற்றைக் காட்டும்.', formula: 'Shall I/We + V1? · Subject + should + V1', examples: [e('Shall we go now?', 'நாம் இப்போது போகலாமா?'), e('Shall I make tea?', 'நான் தேநீர் தயாரிக்கட்டுமா?'), e('You should drink more water.', 'நீங்கள் அதிக தண்ணீர் குடிக்க வேண்டும்.')], remember: ['Shall பெரும்பாலும் I/We உடன் கேள்வியாக வரும்.', 'Should என்பது ஆலோசனை; must அளவுக்கு கட்டாயம் இல்லை.'], practice: 'Shall I…? கொண்டு இரண்டு உதவிகளையும், should கொண்டு இரண்டு ஆலோசனைகளையும் சொல்லுங்கள்.' },
  { day: 24, title: 'May & Might', tamil: 'May மற்றும் Might', emoji: '🌦️', videoId: '6E8OK4aSHTA', explanation: 'May, might இரண்டும் வாய்ப்பைக் காட்டும். May அனுமதி கேட்கவும் பயன்படும்; might இன்னும் குறைந்த வாய்ப்பைக் குறிக்கலாம்.', formula: 'Subject + may/might + V1 · May I + V1?', examples: [e('May I come in?', 'நான் உள்ளே வரலாமா?'), e('It may rain today.', 'இன்று மழை பெய்யலாம்.'), e('She might come later.', 'அவள் பின்னர் வரக்கூடும்.')], remember: ['May I…? என்பது மரியாதையான அனுமதி கேள்வி.', 'may/might-க்கு அடுத்து V1.'], practice: 'அனுமதி கேட்க May I…? கொண்டு 2 கேள்விகளும், வாய்ப்பைப் பற்றி 2 வாக்கியங்களும் சொல்லுங்கள்.' },
  { day: 25, title: 'Must', tamil: 'Must பயன்பாடு', emoji: '❗', videoId: 'k69LSysP7NI', explanation: 'மிக முக்கியமான கட்டாயம், விதி அல்லது உறுதியான முடிவை must காட்டுகிறது. Must not என்பது செய்யவே கூடாது.', formula: 'Subject + must + V1 · must not/mustn’t + V1', examples: [e('You must take your medicine.', 'நீங்கள் கட்டாயம் மருந்து எடுத்துக்கொள்ள வேண்டும்.'), e('We must leave now.', 'நாம் இப்போது கட்டாயம் கிளம்ப வேண்டும்.'), e('You must not touch this.', 'நீங்கள் இதைத் தொடக்கூடாது.')], remember: ['Must not = கூடாது; don’t have to = அவசியமில்லை—இவை வேறு.', 'Must-க்கு அடுத்து V1.'], practice: 'வீட்டில் பாதுகாப்பாக இருக்க வேண்டிய 4 விதிகளை must/must not கொண்டு சொல்லுங்கள்.' },
  { day: 26, title: 'Semi-modal Verbs', tamil: 'Semi-modal வினைச்சொற்கள்', emoji: '🪜', videoId: '7cLlatiFJgM', explanation: 'have to, need to, ought to, used to போன்றவை modal போலவே தேவை, ஆலோசனை, பழைய பழக்கம் ஆகியவற்றைக் காட்டுகின்றன.', formula: 'have/has to + V1 · need to + V1 · used to + V1', examples: [e('I have to go now.', 'நான் இப்போது செல்ல வேண்டும்.'), e('You need to rest.', 'நீங்கள் ஓய்வெடுக்க வேண்டும்.'), e('I used to walk every morning.', 'நான் முன்பு தினமும் காலையில் நடப்பது வழக்கம்.')], remember: ['He/She உடன் has to.', 'used to என்பது இப்போது இல்லாத பழைய பழக்கம்.'], practice: 'இன்றைய கடமைகள் பற்றி have to கொண்டு 3 வாக்கியங்களும், பழைய பழக்கம் பற்றி used to கொண்டு ஒன்றும் சொல்லுங்கள்.' },
  { day: 27, title: 'This, That, These & Those', tamil: 'இது, அது, இவை, அவை', emoji: '👉', videoId: 'pg96xsCGiKA', explanation: 'அருகில்/தொலைவில் உள்ள ஒன்று அல்லது பலவற்றைக் காட்ட இந்த நான்கு சொற்கள் பயன்படுகின்றன.', formula: 'Near: this (one), these (many) · Far: that (one), those (many)', examples: [e('This is my bag.', 'இது என் பை.'), e('Those are my shoes.', 'அவை என் காலணிகள்.'), e('These flowers are beautiful.', 'இந்தப் பூக்கள் அழகாக உள்ளன.')], remember: ['this/that = ஒன்று; these/those = பல.', 'these என்பதை “தீஸ்”, those என்பதை “தோஸ்” என்று உச்சரிக்கவும்.'], practice: 'அருகிலும் தொலைவிலும் உள்ள பொருட்களைச் சுட்டி நான்கு சொற்களையும் பயன்படுத்துங்கள்.' },
  { day: 28, title: '20 Common Grammar Mistakes', tamil: '20 பொதுவான இலக்கணப் பிழைகள்', emoji: '🛠️', videoId: 'II_uNvXb-Yg', explanation: 'அடிக்கடி வரும் சிறிய பிழைகளைத் திருத்தினால் பேச்சு உடனே தெளிவாகும். Subject–verb agreement, tense, article, preposition ஆகியவற்றை கவனியுங்கள்.', formula: 'Notice → Correct → Repeat aloud', examples: [e('She goes to work. (not “She go”)', 'அவள் வேலைக்குச் செல்கிறாள்.'), e('I did not go. (not “did not went”)', 'நான் செல்லவில்லை.'), e('He is at home. (not “in home”)', 'அவர் வீட்டில் இருக்கிறார்.')], remember: ['Did உடன் V1 மட்டுமே.', 'He/She simple present-ல் verb-க்கு s/es மறக்காதீர்கள்.'], practice: 'உங்களுக்கு அடிக்கடி வரும் 5 பிழைகளை எழுதிச் சரியான வாக்கியத்தை மூன்று முறை சத்தமாகச் சொல்லுங்கள்.' },
  { day: 29, title: 'Would Have & Could Have', tamil: 'Would have, Could have', emoji: '🤔', videoId: 'DCHumWgqZYI', explanation: 'கடந்த காலத்தில் நடக்காத கற்பனை விளைவை would have சொல்கிறது. வாய்ப்பு இருந்தும் செய்யவில்லை அல்லது செய்திருக்க முடியும் என்பதை could have சொல்கிறது.', formula: 'would/could have + V3', examples: [e('I would have come, but I was sick.', 'நான் வந்திருப்பேன், ஆனால் உடல்நிலை சரியில்லை.'), e('She could have called me.', 'அவள் என்னை அழைத்திருக்க முடியும்.'), e('We could have taken the bus.', 'நாம் பேருந்தில் சென்றிருக்க முடியும்.')], remember: ['have-க்கு அடுத்து V3.', 'இது கடந்த காலத்தைப் பற்றிய இன்றைய சிந்தனை.'], practice: 'நேற்று வேறுவிதமாகச் செய்திருக்கக்கூடிய இரண்டு விஷயங்களை could have கொண்டு சொல்லுங்கள்.' },
  { day: 30, title: 'Should Have & Must Have', tamil: 'Should have, Must have', emoji: '🎓', videoId: 'YRBxcd4c9EM', explanation: 'கடந்த காலத்தில் செய்ய வேண்டியது ஆனால் செய்யவில்லை என்பதை should have சொல்கிறது. ஆதாரத்தை வைத்து கடந்த காலத்தை உறுதியாக ஊகிக்க must have பயன்படும்.', formula: 'should/must have + V3', examples: [e('I should have called you.', 'நான் உங்களை அழைத்திருக்க வேண்டும்.'), e('You should have rested.', 'நீங்கள் ஓய்வெடுத்திருக்க வேண்டும்.'), e('She must have forgotten.', 'அவள் மறந்திருக்க வேண்டும்.')], remember: ['Should have = வருத்தம் அல்லது ஆலோசனை.', 'Must have = கடந்த நிகழ்வைப் பற்றிய உறுதியான ஊகம்.'], practice: 'இந்த மாதம் கற்றதை நினைத்து should have கொண்டு ஒன்றும், ஒரு கடந்த நிகழ்வை ஊகித்து must have கொண்டு ஒன்றும் சொல்லுங்கள்.' },
];
