type Example = [string, string];
const word = (word: string, tamilSound: string, tamil: string, meaning: string, kind: string, emoji: string, examples: Example[]) => ({ word, split: word, tamilSound, tamil, meaning, kind, emoji, examples });

export const moreWordCategories = [
  { id: 'small-grammar', name: 'Small Grammar Words', tamil: 'சிறிய இலக்கணச் சொற்கள்', emoji: '🧱', color: '#a56c4f', words: [
    word('A', 'அ', 'ஒரு', 'Used before one general thing that begins with a consonant sound.', 'Article', '1️⃣', [['I have a book.', 'என்னிடம் ஒரு புத்தகம் உள்ளது.'], ['She is a doctor.', 'அவர் ஒரு மருத்துவர்.'], ['This is a car.', 'இது ஒரு கார்.']]),
    word('An', 'ஆன்', 'ஒரு', 'Used before one general thing that begins with a vowel sound.', 'Article', '🍎', [['I ate an apple.', 'நான் ஒரு ஆப்பிள் சாப்பிட்டேன்.'], ['He has an umbrella.', 'அவரிடம் ஒரு குடை உள்ளது.'], ['She is an artist.', 'அவர் ஒரு கலைஞர்.']]),
    word('The', 'த', 'அந்த / குறிப்பிட்ட', 'Used when speaking about a particular person or thing.', 'Article', '👉', [['Open the door.', 'அந்தக் கதவைத் திறக்கவும்.'], ['The sun is hot.', 'சூரியன் சூடாக உள்ளது.'], ['The book is on the table.', 'புத்தகம் மேசையின் மேல் உள்ளது.']]),
    word('And', 'ஆண்ட்', 'மற்றும் / உம்', 'Joins words or ideas together.', 'Conjunction', '➕', [['I like tea and coffee.', 'எனக்கு தேநீரும் காபியும் பிடிக்கும்.'], ['He and she are friends.', 'அவரும் அவளும் நண்பர்கள்.'], ['The bag is small and light.', 'பை சிறியதாகவும் லேசாகவும் உள்ளது.']]),
    word('But', 'பட்', 'ஆனால்', 'Joins two different or opposite ideas.', 'Conjunction', '↔️', [['I am tired but happy.', 'நான் சோர்வாக இருக்கிறேன், ஆனால் மகிழ்ச்சியாக இருக்கிறேன்.'], ['It is small but strong.', 'இது சிறியது, ஆனால் வலிமையானது.'], ['She called, but I was busy.', 'அவர் அழைத்தார், ஆனால் நான் வேலையாக இருந்தேன்.']]),
    word('Or', 'ஆர்', 'அல்லது', 'Shows a choice between things.', 'Conjunction', '🔀', [['Tea or coffee?', 'தேநீரா அல்லது காபியா?'], ['Come now or call later.', 'இப்போது வாருங்கள் அல்லது பிறகு அழையுங்கள்.'], ['Is it big or small?', 'இது பெரியதா அல்லது சிறியதா?']]),
    word('Because', 'பி-காஸ்', 'ஏனெனில்', 'Gives the reason for something.', 'Conjunction', '💡', [['I stayed home because I was tired.', 'நான் சோர்வாக இருந்ததால் வீட்டில் இருந்தேன்.'], ['She is happy because she won.', 'அவர் வென்றதால் மகிழ்ச்சியாக இருக்கிறார்.'], ['I drink water because it is healthy.', 'தண்ணீர் ஆரோக்கியமானதால் நான் அதைக் குடிக்கிறேன்.']]),
    word('If', 'இஃப்', 'என்றால்', 'Introduces a possible condition.', 'Conjunction', '🤔', [['Call me if you need help.', 'உங்களுக்கு உதவி தேவைப்பட்டால் என்னை அழையுங்கள்.'], ['If it rains, stay inside.', 'மழை பெய்தால் உள்ளே இருங்கள்.'], ['I will come if I can.', 'என்னால் முடிந்தால் நான் வருவேன்.']]),
  ]},
  { id: 'position-words', name: 'Position Words', tamil: 'இடத்தைக் குறிக்கும் சொற்கள்', emoji: '📍', color: '#4f8f85', words: [
    word('In', 'இன்', 'உள்ளே / இல்', 'Inside a place, area, or container.', 'Preposition', '📥', [['The book is in the bag.', 'புத்தகம் பையில் உள்ளது.'], ['She lives in Chennai.', 'அவர் சென்னையில் வசிக்கிறார்.'], ['Put the rice in the bowl.', 'சாதத்தை கிண்ணத்தில் வையுங்கள்.']]),
    word('On', 'ஆன்', 'மேல்', 'Touching or resting on the surface of something.', 'Preposition', '⬆️', [['The phone is on the table.', 'கைப்பேசி மேசையின் மேல் உள்ளது.'], ['The picture is on the wall.', 'படம் சுவரில் உள்ளது.'], ['Put the bag on the chair.', 'பையை நாற்காலியின் மேல் வையுங்கள்.']]),
    word('At', 'அட்', 'இல் / அருகில் / மணிக்கு', 'Used for an exact place or time.', 'Preposition', '🎯', [['I am at home.', 'நான் வீட்டில் இருக்கிறேன்.'], ['Meet me at the shop.', 'கடையில் என்னைச் சந்தியுங்கள்.'], ['Class starts at two.', 'வகுப்பு இரண்டு மணிக்குத் தொடங்குகிறது.']]),
    word('Under', 'அண்டர்', 'கீழே', 'In a lower position than something.', 'Preposition', '⬇️', [['The cat is under the chair.', 'பூனை நாற்காலியின் கீழே உள்ளது.'], ['The shoes are under the bed.', 'காலணிகள் படுக்கையின் கீழே உள்ளன.'], ['Sit under the tree.', 'மரத்தின் கீழே உட்காருங்கள்.']]),
    word('Over', 'ஓவர்', 'மேலே / கடந்து', 'Above something or moving across it.', 'Preposition', '🌉', [['The plane flew over the town.', 'விமானம் நகரத்தின் மேலே பறந்தது.'], ['Put a cloth over the box.', 'பெட்டியின் மேல் ஒரு துணியைப் போடுங்கள்.'], ['The bridge goes over the river.', 'பாலம் ஆற்றின் மேலே செல்கிறது.']]),
    word('Between', 'பி-ட்வீன்', 'இடையில்', 'In the middle of two people or things.', 'Preposition', '↔️', [['The shop is between two houses.', 'கடை இரண்டு வீடுகளுக்கு இடையில் உள்ளது.'], ['Sit between us.', 'எங்களுக்கு இடையில் உட்காருங்கள்.'], ['The ball is between the boxes.', 'பந்து பெட்டிகளுக்கு இடையில் உள்ளது.']]),
    word('Behind', 'பி-ஹைண்ட்', 'பின்னால்', 'At the back of someone or something.', 'Preposition', '🔙', [['The garden is behind the house.', 'தோட்டம் வீட்டின் பின்னால் உள்ளது.'], ['She is standing behind me.', 'அவர் எனக்குப் பின்னால் நிற்கிறார்.'], ['The bag is behind the door.', 'பை கதவின் பின்னால் உள்ளது.']]),
    word('Inside', 'இன்-சைட்', 'உள்ளே', 'In the inner part of a place or thing.', 'Preposition / Adverb', '🏠', [['Please come inside.', 'தயவுசெய்து உள்ளே வாருங்கள்.'], ['The keys are inside the box.', 'சாவிகள் பெட்டிக்குள் உள்ளன.'], ['Stay inside the room.', 'அறைக்குள் இருங்கள்.']]),
  ]},
  { id: 'time-words', name: 'Time Words', tamil: 'நேரத்தைக் குறிக்கும் சொற்கள்', emoji: '🕐', color: '#b07b3e', words: [
    word('Today', 'டு-டே', 'இன்று', 'The present day.', 'Time word', '☀️', [['Today is Monday.', 'இன்று திங்கட்கிழமை.'], ['I am happy today.', 'நான் இன்று மகிழ்ச்சியாக இருக்கிறேன்.'], ['We have class today.', 'இன்று நமக்கு வகுப்பு உள்ளது.']]),
    word('Tomorrow', 'டு-மாரோ', 'நாளை', 'The day after today.', 'Time word', '🌅', [['I will come tomorrow.', 'நான் நாளை வருவேன்.'], ['The shop opens tomorrow.', 'கடை நாளை திறக்கும்.'], ['See you tomorrow.', 'நாளை சந்திப்போம்.']]),
    word('Yesterday', 'யெஸ்-டர்-டே', 'நேற்று', 'The day before today.', 'Time word', '🌇', [['I called you yesterday.', 'நான் உங்களை நேற்று அழைத்தேன்.'], ['Yesterday was Sunday.', 'நேற்று ஞாயிற்றுக்கிழமை.'], ['She was tired yesterday.', 'அவர் நேற்று சோர்வாக இருந்தார்.']]),
    word('Now', 'நவ்', 'இப்போது', 'At the present moment.', 'Time word', '⏱️', [['Come here now.', 'இப்போது இங்கே வாருங்கள்.'], ['I am busy now.', 'நான் இப்போது வேலையாக இருக்கிறேன்.'], ['We can eat now.', 'நாம் இப்போது சாப்பிடலாம்.']]),
    word('Later', 'லேட்டர்', 'பிறகு', 'At a time after now.', 'Time word', '⏩', [['I will call you later.', 'நான் உங்களைப் பிறகு அழைப்பேன்.'], ['We can talk later.', 'நாம் பிறகு பேசலாம்.'], ['Finish it later.', 'அதைப் பிறகு முடிக்கவும்.']]),
    word('Before', 'பி-ஃபோர்', 'முன்பு / முன்னால்', 'Earlier than a particular time or event.', 'Time word / Preposition', '⏪', [['Wash your hands before eating.', 'சாப்பிடுவதற்கு முன்பு கைகளைக் கழுவுங்கள்.'], ['I have seen her before.', 'நான் அவரை முன்பு பார்த்திருக்கிறேன்.'], ['Come before six.', 'ஆறு மணிக்கு முன்பு வாருங்கள்.']]),
    word('After', 'ஆஃப்டர்', 'பிறகு', 'Later than a particular time or event.', 'Time word / Preposition', '⏩', [['Rest after lunch.', 'மதிய உணவிற்குப் பிறகு ஓய்வெடுங்கள்.'], ['Call me after class.', 'வகுப்பிற்குப் பிறகு என்னை அழையுங்கள்.'], ['We play after school.', 'பள்ளிக்குப் பிறகு நாங்கள் விளையாடுவோம்.']]),
    word('Always', 'ஆல்-வேஸ்', 'எப்போதும்', 'At every time or on every occasion.', 'Frequency word', '🔁', [['I always drink water.', 'நான் எப்போதும் தண்ணீர் குடிப்பேன்.'], ['She is always kind.', 'அவர் எப்போதும் அன்பானவர்.'], ['Always tell the truth.', 'எப்போதும் உண்மையைச் சொல்லுங்கள்.']]),
  ]},
  { id: 'useful-verbs', name: 'More Useful Verbs', tamil: 'மேலும் பயனுள்ள வினைச்சொற்கள்', emoji: '🛠️', color: '#587cab', words: [
    word('Make', 'மேக்', 'செய் / உருவாக்கு', 'To create or produce something.', 'Verb', '🔨', [['I make tea every morning.', 'நான் தினமும் காலையில் தேநீர் செய்கிறேன்.'], ['She makes a cake.', 'அவர் ஒரு கேக் செய்கிறார்.'], ['Let us make a plan.', 'நாம் ஒரு திட்டம் உருவாக்கலாம்.']]),
    word('Take', 'டேக்', 'எடு / எடுத்துக்கொள்', 'To move or carry something with you.', 'Verb', '🤲', [['Take this book.', 'இந்தப் புத்தகத்தை எடுத்துக்கொள்ளுங்கள்.'], ['I take the bus to school.', 'நான் பள்ளிக்கு பேருந்தில் செல்வேன்.'], ['Please take some food.', 'தயவுசெய்து கொஞ்சம் உணவு எடுத்துக்கொள்ளுங்கள்.']]),
    word('Give', 'கிவ்', 'கொடு', 'To hand or provide something to someone.', 'Verb', '🎁', [['Give me the pen.', 'பேனாவை எனக்குக் கொடுங்கள்.'], ['I give her some water.', 'நான் அவருக்குக் கொஞ்சம் தண்ணீர் கொடுக்கிறேன்.'], ['Please give him the book.', 'தயவுசெய்து அவருக்குப் புத்தகத்தைக் கொடுங்கள்.']]),
    word('Get', 'கெட்', 'பெறு / எடுத்துவா', 'To receive, obtain, or bring something.', 'Verb', '📦', [['I get a message every day.', 'எனக்கு தினமும் ஒரு செய்தி வருகிறது.'], ['Please get some water.', 'தயவுசெய்து கொஞ்சம் தண்ணீர் எடுத்துவாருங்கள்.'], ['She gets home at six.', 'அவர் ஆறு மணிக்கு வீட்டிற்கு வருகிறார்.']]),
    word('Put', 'புட்', 'வை', 'To place something in a position.', 'Verb', '📍', [['Put the bag here.', 'பையை இங்கே வையுங்கள்.'], ['Put the book on the table.', 'புத்தகத்தை மேசையின் மேல் வையுங்கள்.'], ['She puts rice in the bowl.', 'அவர் சாதத்தைக் கிண்ணத்தில் வைக்கிறார்.']]),
    word('Bring', 'பிரிங்', 'கொண்டுவா', 'To carry something toward a person or place.', 'Verb', '👜', [['Please bring your book.', 'தயவுசெய்து உங்கள் புத்தகத்தைக் கொண்டுவாருங்கள்.'], ['Bring me some water.', 'எனக்குக் கொஞ்சம் தண்ணீர் கொண்டுவாருங்கள்.'], ['She brings food from home.', 'அவர் வீட்டிலிருந்து உணவு கொண்டுவருகிறார்.']]),
    word('Want', 'வான்ட்', 'விரும்பு / வேண்டும்', 'To wish to have or do something.', 'Verb', '💭', [['I want some water.', 'எனக்குக் கொஞ்சம் தண்ணீர் வேண்டும்.'], ['She wants to learn English.', 'அவர் ஆங்கிலம் கற்க விரும்புகிறார்.'], ['What do you want?', 'உங்களுக்கு என்ன வேண்டும்?']]),
    word('Need', 'நீட்', 'தேவை', 'To require something because it is important or necessary.', 'Verb', '❗', [['I need your help.', 'எனக்கு உங்கள் உதவி தேவை.'], ['We need some food.', 'நமக்குக் கொஞ்சம் உணவு தேவை.'], ['Do you need a doctor?', 'உங்களுக்கு மருத்துவர் தேவையா?']]),
  ]},
];
