'use client';

import { useEffect, useMemo, useState } from 'react';

type Word = { word: string; split: string; tamilSound: string; tamil: string; meaning: string; kind: string; emoji: string; examples: [string, string][] };
type Category = { id: string; name: string; tamil: string; emoji: string; color: string; words: Word[] };

const categories: Category[] = [
  { id: 'home', name: 'Home & Family', tamil: 'வீடும் குடும்பமும்', emoji: '🏡', color: '#ef8354', words: [
    { word: 'Home', split: 'Home', tamilSound: 'ஹோம்', tamil: 'வீடு', meaning: 'The place where you live.', kind: 'Noun', emoji: '🏠', examples: [['I am at home.', 'நான் வீட்டில் இருக்கிறேன்.'], ['Our home is small.', 'எங்கள் வீடு சிறியது.'], ['Let us go home.', 'நாம் வீட்டிற்குப் போகலாம்.']] },
    { word: 'Family', split: 'Fam-i-ly', tamilSound: 'ஃபேம்-இ-லி', tamil: 'குடும்பம்', meaning: 'People related to one another.', kind: 'Noun', emoji: '👨‍👩‍👧', examples: [['I love my family.', 'நான் என் குடும்பத்தை நேசிக்கிறேன்.'], ['My family is here.', 'என் குடும்பம் இங்கே இருக்கிறது.'], ['We eat as a family.', 'நாங்கள் குடும்பமாகச் சாப்பிடுகிறோம்.']] },
    { word: 'Mother', split: 'Moth-er', tamilSound: 'மதர்', tamil: 'அம்மா', meaning: 'A female parent.', kind: 'Noun', emoji: '👩', examples: [['My mother is kind.', 'என் அம்மா அன்பானவர்.'], ['Mother is cooking.', 'அம்மா சமைக்கிறார்.'], ['I called my mother.', 'நான் என் அம்மாவை அழைத்தேன்.']] },
    { word: 'Door', split: 'Door', tamilSound: 'டோர்', tamil: 'கதவு', meaning: 'The part that opens and closes an entrance.', kind: 'Noun', emoji: '🚪', examples: [['Open the door.', 'கதவைத் திறக்கவும்.'], ['The door is brown.', 'கதவு பழுப்பு நிறத்தில் உள்ளது.'], ['Please close the door.', 'தயவுசெய்து கதவை மூடுங்கள்.']] },
    { word: 'Room', split: 'Room', tamilSound: 'ரூம்', tamil: 'அறை', meaning: 'A part of a building with walls.', kind: 'Noun', emoji: '🛋️', examples: [['This is my room.', 'இது என் அறை.'], ['The room is clean.', 'அறை சுத்தமாக உள்ளது.'], ['Come into the room.', 'அறைக்குள் வாருங்கள்.']] },
    { word: 'Help', split: 'Help', tamilSound: 'ஹெல்ப்', tamil: 'உதவி', meaning: 'To make something easier for someone.', kind: 'Verb', emoji: '🤝', examples: [['Please help me.', 'தயவுசெய்து எனக்கு உதவுங்கள்.'], ['Can I help you?', 'நான் உங்களுக்கு உதவலாமா?'], ['She helps her mother.', 'அவள் தன் அம்மாவுக்கு உதவுகிறாள்.']] },
  ]},
  { id: 'food', name: 'Food & Cooking', tamil: 'உணவும் சமையலும்', emoji: '🥣', color: '#e3a23a', words: [
    { word: 'Water', split: 'Wa-ter', tamilSound: 'வா-டர்', tamil: 'தண்ணீர்', meaning: 'The clear liquid that we drink.', kind: 'Noun', emoji: '💧', examples: [['Please give me water.', 'தயவுசெய்து எனக்கு தண்ணீர் கொடுங்கள்.'], ['I drink water every morning.', 'நான் தினமும் காலையில் தண்ணீர் குடிப்பேன்.'], ['The water is hot.', 'தண்ணீர் சூடாக இருக்கிறது.']] },
    { word: 'Food', split: 'Food', tamilSound: 'ஃபூட்', tamil: 'உணவு', meaning: 'What people eat.', kind: 'Noun', emoji: '🍛', examples: [['The food is ready.', 'உணவு தயாராக உள்ளது.'], ['This food is tasty.', 'இந்த உணவு சுவையாக இருக்கிறது.'], ['We need some food.', 'நமக்கு கொஞ்சம் உணவு தேவை.']] },
    { word: 'Rice', split: 'Rice', tamilSound: 'ரைஸ்', tamil: 'அரிசி / சாதம்', meaning: 'A small grain cooked as food.', kind: 'Noun', emoji: '🍚', examples: [['I eat rice for lunch.', 'நான் மதிய உணவிற்கு சாதம் சாப்பிடுகிறேன்.'], ['The rice is warm.', 'சாதம் சூடாக இருக்கிறது.'], ['Please cook the rice.', 'தயவுசெய்து சாதத்தை சமைக்கவும்.']] },
    { word: 'Cook', split: 'Cook', tamilSound: 'குக்', tamil: 'சமை', meaning: 'To prepare food using heat.', kind: 'Verb', emoji: '🍳', examples: [['I cook every day.', 'நான் தினமும் சமைக்கிறேன்.'], ['Can you cook rice?', 'உங்களால் சாதம் சமைக்க முடியுமா?'], ['She cooks very well.', 'அவள் நன்றாக சமைக்கிறாள்.']] },
    { word: 'Eat', split: 'Eat', tamilSound: 'ஈட்', tamil: 'சாப்பிடு', meaning: 'To put food in your mouth and swallow it.', kind: 'Verb', emoji: '🥄', examples: [['Let us eat now.', 'இப்போது நாம் சாப்பிடலாம்.'], ['I eat a banana.', 'நான் ஒரு வாழைப்பழம் சாப்பிடுகிறேன்.'], ['Please eat slowly.', 'தயவுசெய்து மெதுவாக சாப்பிடுங்கள்.']] },
    { word: 'Taste', split: 'Taste', tamilSound: 'டேஸ்ட்', tamil: 'சுவை', meaning: 'The flavour of food or drink.', kind: 'Noun / Verb', emoji: '😋', examples: [['Taste this soup.', 'இந்த சூப்பை சுவைத்துப் பாருங்கள்.'], ['It tastes sweet.', 'இது இனிப்பாக இருக்கிறது.'], ['I like the taste.', 'எனக்கு இந்த சுவை பிடிக்கும்.']] },
  ]},
  { id: 'health', name: 'Body & Health', tamil: 'உடலும் உடல்நலமும்', emoji: '🫶', color: '#db6f78', words: [
    { word: 'Head', split: 'Head', tamilSound: 'ஹெட்', tamil: 'தலை', meaning: 'The top part of your body.', kind: 'Noun', emoji: '🙂', examples: [['My head hurts.', 'என் தலை வலிக்கிறது.'], ['Turn your head.', 'உங்கள் தலையைத் திருப்புங்கள்.'], ['Keep your head up.', 'உங்கள் தலையை நிமிர்த்தி வையுங்கள்.']] },
    { word: 'Hand', split: 'Hand', tamilSound: 'ஹேண்ட்', tamil: 'கை', meaning: 'The part at the end of your arm.', kind: 'Noun', emoji: '✋', examples: [['Wash your hands.', 'உங்கள் கைகளைக் கழுவுங்கள்.'], ['Give me your hand.', 'உங்கள் கையை என்னிடம் கொடுங்கள்.'], ['My hand is cold.', 'என் கை குளிராக இருக்கிறது.']] },
    { word: 'Walk', split: 'Walk', tamilSound: 'வாக்', tamil: 'நட', meaning: 'To move forward on your feet.', kind: 'Verb', emoji: '🚶‍♀️', examples: [['I walk every morning.', 'நான் தினமும் காலையில் நடக்கிறேன்.'], ['Let us walk home.', 'நாம் வீட்டிற்கு நடந்து செல்லலாம்.'], ['Walk slowly, please.', 'தயவுசெய்து மெதுவாக நடங்கள்.']] },
    { word: 'Pain', split: 'Pain', tamilSound: 'பெயின்', tamil: 'வலி', meaning: 'An unpleasant feeling in the body.', kind: 'Noun', emoji: '🤕', examples: [['I have back pain.', 'எனக்கு முதுகு வலி உள்ளது.'], ['Where is the pain?', 'வலி எங்கே இருக்கிறது?'], ['The pain is less now.', 'இப்போது வலி குறைவாக உள்ளது.']] },
    { word: 'Doctor', split: 'Doc-tor', tamilSound: 'டாக்-டர்', tamil: 'மருத்துவர்', meaning: 'A person trained to treat illness.', kind: 'Noun', emoji: '🩺', examples: [['I need a doctor.', 'எனக்கு ஒரு மருத்துவர் தேவை.'], ['The doctor is here.', 'மருத்துவர் இங்கே இருக்கிறார்.'], ['Please call the doctor.', 'தயவுசெய்து மருத்துவரை அழைக்கவும்.']] },
    { word: 'Healthy', split: 'Health-y', tamilSound: 'ஹெல்த்-தி', tamil: 'ஆரோக்கியமான', meaning: 'Well and not sick.', kind: 'Adjective', emoji: '💪', examples: [['I feel healthy.', 'நான் ஆரோக்கியமாக உணர்கிறேன்.'], ['This is healthy food.', 'இது ஆரோக்கியமான உணவு.'], ['Walking keeps us healthy.', 'நடைப்பயிற்சி நம்மை ஆரோக்கியமாக வைக்கிறது.']] },
  ]},
  { id: 'feelings', name: 'Feelings', tamil: 'உணர்வுகள்', emoji: '🌻', color: '#9a6fb0', words: [
    { word: 'Happy', split: 'Hap-py', tamilSound: 'ஹேப்-பி', tamil: 'மகிழ்ச்சி', meaning: 'Feeling pleased and joyful.', kind: 'Adjective', emoji: '😊', examples: [['I am very happy.', 'நான் மிகவும் மகிழ்ச்சியாக இருக்கிறேன்.'], ['You look happy.', 'நீங்கள் மகிழ்ச்சியாகத் தெரிகிறீர்கள்.'], ['This makes me happy.', 'இது என்னை மகிழ்ச்சிப்படுத்துகிறது.']] },
    { word: 'Sad', split: 'Sad', tamilSound: 'சேட்', tamil: 'சோகம்', meaning: 'Feeling unhappy.', kind: 'Adjective', emoji: '😔', examples: [['Why are you sad?', 'நீங்கள் ஏன் சோகமாக இருக்கிறீர்கள்?'], ['I feel sad today.', 'இன்று நான் சோகமாக உணர்கிறேன்.'], ['Do not be sad.', 'சோகமாக இருக்காதீர்கள்.']] },
    { word: 'Love', split: 'Love', tamilSound: 'லவ்', tamil: 'அன்பு', meaning: 'A strong feeling of care.', kind: 'Noun / Verb', emoji: '❤️', examples: [['I love my family.', 'நான் என் குடும்பத்தை நேசிக்கிறேன்.'], ['Love gives us strength.', 'அன்பு நமக்கு வலிமை தருகிறது.'], ['They love this place.', 'அவர்களுக்கு இந்த இடம் மிகவும் பிடிக்கும்.']] },
    { word: 'Tired', split: 'Tired', tamilSound: 'டையர்ட்', tamil: 'சோர்வாக', meaning: 'Needing rest or sleep.', kind: 'Adjective', emoji: '🥱', examples: [['I am tired now.', 'நான் இப்போது சோர்வாக இருக்கிறேன்.'], ['Are you tired?', 'நீங்கள் சோர்வாக இருக்கிறீர்களா?'], ['She looks tired.', 'அவள் சோர்வாகத் தெரிகிறாள்.']] },
    { word: 'Afraid', split: 'A-fraid', tamilSound: 'அ-ஃப்ரெய்ட்', tamil: 'பயமாக', meaning: 'Feeling fear or worry.', kind: 'Adjective', emoji: '😟', examples: [['Do not be afraid.', 'பயப்படாதீர்கள்.'], ['I am afraid of dogs.', 'எனக்கு நாய்களைக் கண்டால் பயம்.'], ['She feels afraid.', 'அவள் பயப்படுகிறாள்.']] },
    { word: 'Calm', split: 'Calm', tamilSound: 'காம்', tamil: 'அமைதியான', meaning: 'Peaceful and not worried.', kind: 'Adjective', emoji: '😌', examples: [['Please stay calm.', 'தயவுசெய்து அமைதியாக இருங்கள்.'], ['The room is calm.', 'அறை அமைதியாக உள்ளது.'], ['I feel calm now.', 'இப்போது நான் அமைதியாக உணர்கிறேன்.']] },
  ]},
  { id: 'places', name: 'Places & Directions', tamil: 'இடங்களும் திசைகளும்', emoji: '🧭', color: '#4f8f85', words: [
    { word: 'Here', split: 'Here', tamilSound: 'ஹியர்', tamil: 'இங்கே', meaning: 'In or at this place.', kind: 'Adverb', emoji: '📍', examples: [['Please come here.', 'தயவுசெய்து இங்கே வாருங்கள்.'], ['Keep the bag here.', 'பையை இங்கே வையுங்கள்.'], ['I live here.', 'நான் இங்கே வசிக்கிறேன்.']] },
    { word: 'Near', split: 'Near', tamilSound: 'நியர்', tamil: 'அருகில்', meaning: 'Not far away.', kind: 'Adjective / Adverb', emoji: '↔️', examples: [['The shop is near.', 'கடை அருகில் உள்ளது.'], ['Sit near me.', 'என் அருகில் உட்காருங்கள்.'], ['Is there a hospital near here?', 'இங்கே அருகில் மருத்துவமனை உள்ளதா?']] },
    { word: 'Left', split: 'Left', tamilSound: 'லெஃப்ட்', tamil: 'இடது', meaning: 'The direction opposite to right.', kind: 'Noun / Adjective', emoji: '⬅️', examples: [['Turn left here.', 'இங்கே இடதுபுறம் திரும்புங்கள்.'], ['It is on your left.', 'அது உங்கள் இடதுபுறத்தில் உள்ளது.'], ['Look to the left.', 'இடதுபுறம் பாருங்கள்.']] },
    { word: 'Right', split: 'Right', tamilSound: 'ரைட்', tamil: 'வலது / சரி', meaning: 'The direction opposite to left; also correct.', kind: 'Adjective', emoji: '➡️', examples: [['Turn right at the road.', 'சாலையில் வலதுபுறம் திரும்புங்கள்.'], ['Your answer is right.', 'உங்கள் பதில் சரியானது.'], ['The bank is on the right.', 'வங்கி வலதுபுறத்தில் உள்ளது.']] },
    { word: 'Road', split: 'Road', tamilSound: 'ரோட்', tamil: 'சாலை', meaning: 'A way for vehicles and people.', kind: 'Noun', emoji: '🛣️', examples: [['Cross the road carefully.', 'சாலையை கவனமாகக் கடக்கவும்.'], ['This road is busy.', 'இந்த சாலை பரபரப்பாக உள்ளது.'], ['The road is long.', 'சாலை நீளமாக உள்ளது.']] },
    { word: 'Shop', split: 'Shop', tamilSound: 'ஷாப்', tamil: 'கடை', meaning: 'A place where things are sold.', kind: 'Noun', emoji: '🏪', examples: [['I am going to the shop.', 'நான் கடைக்குப் போகிறேன்.'], ['The shop is open.', 'கடை திறந்திருக்கிறது.'], ['This shop sells fruit.', 'இந்தக் கடையில் பழங்கள் விற்கப்படுகின்றன.']] },
  ]},
  { id: 'actions', name: 'Everyday Actions', tamil: 'அன்றாட செயல்கள்', emoji: '✨', color: '#557ab0', words: [
    { word: 'Come', split: 'Come', tamilSound: 'கம்', tamil: 'வா', meaning: 'To move toward someone or something.', kind: 'Verb', emoji: '👋', examples: [['Please come inside.', 'தயவுசெய்து உள்ளே வாருங்கள்.'], ['Come with me.', 'என்னுடன் வாருங்கள்.'], ['Can you come tomorrow?', 'நீங்கள் நாளை வர முடியுமா?']] },
    { word: 'Go', split: 'Go', tamilSound: 'கோ', tamil: 'போ', meaning: 'To move to another place.', kind: 'Verb', emoji: '🚶', examples: [['Let us go now.', 'இப்போது நாம் போகலாம்.'], ['I go to work.', 'நான் வேலைக்குப் போகிறேன்.'], ['Go straight ahead.', 'நேராக முன்னால் செல்லுங்கள்.']] },
    { word: 'Speak', split: 'Speak', tamilSound: 'ஸ்பீக்', tamil: 'பேசு', meaning: 'To say words using your voice.', kind: 'Verb', emoji: '🗣️', examples: [['Please speak slowly.', 'தயவுசெய்து மெதுவாகப் பேசுங்கள்.'], ['I speak Tamil.', 'நான் தமிழ் பேசுகிறேன்.'], ['Can I speak to her?', 'நான் அவரிடம் பேசலாமா?']] },
    { word: 'Read', split: 'Read', tamilSound: 'ரீட்', tamil: 'படி', meaning: 'To look at and understand written words.', kind: 'Verb', emoji: '📖', examples: [['I read every day.', 'நான் தினமும் படிக்கிறேன்.'], ['Please read this word.', 'தயவுசெய்து இந்த வார்த்தையைப் படியுங்கள்.'], ['She can read English.', 'அவரால் ஆங்கிலம் படிக்க முடியும்.']] },
    { word: 'Listen', split: 'Lis-ten', tamilSound: 'லிஸ்-சன்', tamil: 'கேள்', meaning: 'To pay attention to a sound.', kind: 'Verb', emoji: '👂', examples: [['Listen to me.', 'நான் சொல்வதைக் கேளுங்கள்.'], ['Please listen carefully.', 'தயவுசெய்து கவனமாகக் கேளுங்கள்.'], ['I listen to music.', 'நான் இசை கேட்கிறேன்.']] },
    { word: 'Wait', split: 'Wait', tamilSound: 'வெய்ட்', tamil: 'காத்திரு', meaning: 'To stay until something happens.', kind: 'Verb', emoji: '⏳', examples: [['Please wait here.', 'தயவுசெய்து இங்கே காத்திருங்கள்.'], ['Wait for five minutes.', 'ஐந்து நிமிடங்கள் காத்திருங்கள்.'], ['I will wait for you.', 'நான் உங்களுக்காகக் காத்திருப்பேன்.']] },
  ]},
  { id: 'questions', name: 'Question Words', tamil: 'கேள்விச் சொற்கள்', emoji: '❓', color: '#b56a78', words: [
    { word: 'Who', split: 'Who', tamilSound: 'ஹூ', tamil: 'யார்', meaning: 'Used to ask about a person.', kind: 'Question word', emoji: '👤', examples: [['Who is she?', 'அவள் யார்?'], ['Who called me?', 'என்னை அழைத்தது யார்?'], ['Who is at the door?', 'கதவுக்கு அருகில் யார் இருக்கிறார்?']] },
    { word: 'What', split: 'What', tamilSound: 'வாட்', tamil: 'என்ன', meaning: 'Used to ask about a thing or idea.', kind: 'Question word', emoji: '💭', examples: [['What is this?', 'இது என்ன?'], ['What do you need?', 'உங்களுக்கு என்ன வேண்டும்?'], ['What is your name?', 'உங்கள் பெயர் என்ன?']] },
    { word: 'When', split: 'When', tamilSound: 'வென்', tamil: 'எப்போது', meaning: 'Used to ask about time.', kind: 'Question word', emoji: '🕐', examples: [['When will you come?', 'நீங்கள் எப்போது வருவீர்கள்?'], ['When does the shop open?', 'கடை எப்போது திறக்கும்?'], ['When can we eat?', 'நாம் எப்போது சாப்பிடலாம்?']] },
    { word: 'Where', split: 'Where', tamilSound: 'வேர்', tamil: 'எங்கே', meaning: 'Used to ask about a place.', kind: 'Question word', emoji: '📍', examples: [['Where are you?', 'நீங்கள் எங்கே இருக்கிறீர்கள்?'], ['Where is my bag?', 'என் பை எங்கே?'], ['Where do they live?', 'அவர்கள் எங்கே வசிக்கிறார்கள்?']] },
    { word: 'Why', split: 'Why', tamilSound: 'வை', tamil: 'ஏன்', meaning: 'Used to ask for a reason.', kind: 'Question word', emoji: '🤔', examples: [['Why are you sad?', 'நீங்கள் ஏன் சோகமாக இருக்கிறீர்கள்?'], ['Why is the door open?', 'கதவு ஏன் திறந்திருக்கிறது?'], ['Why did she leave?', 'அவள் ஏன் சென்றாள்?']] },
    { word: 'How', split: 'How', tamilSound: 'ஹவ்', tamil: 'எப்படி', meaning: 'Used to ask about the way something happens.', kind: 'Question word', emoji: '🛠️', examples: [['How are you?', 'நீங்கள் எப்படி இருக்கிறீர்கள்?'], ['How does this work?', 'இது எப்படி வேலை செய்கிறது?'], ['How can I help?', 'நான் எப்படி உதவ முடியும்?']] },
    { word: 'Which', split: 'Which', tamilSound: 'விச்', tamil: 'எது / எந்த', meaning: 'Used to ask someone to choose.', kind: 'Question word', emoji: '↔️', examples: [['Which one is yours?', 'இதில் எது உங்களுடையது?'], ['Which road is right?', 'எந்தச் சாலை சரியானது?'], ['Which colour do you like?', 'உங்களுக்கு எந்த நிறம் பிடிக்கும்?']] },
    { word: 'Whose', split: 'Whose', tamilSound: 'ஹூஸ்', tamil: 'யாருடைய', meaning: 'Used to ask who owns something.', kind: 'Question word', emoji: '🏷️', examples: [['Whose bag is this?', 'இது யாருடைய பை?'], ['Whose phone is ringing?', 'யாருடைய தொலைபேசி ஒலிக்கிறது?'], ['Whose turn is it?', 'இது யாருடைய முறை?']] },
  ]},
  { id: 'pronouns', name: 'People & Pronouns', tamil: 'மக்களும் பிரதிப்பெயர்களும்', emoji: '👥', color: '#617cad', words: [
    { word: 'I', split: 'I', tamilSound: 'ஐ', tamil: 'நான்', meaning: 'The word you use for yourself.', kind: 'Pronoun', emoji: '🙋', examples: [['I am ready.', 'நான் தயாராக இருக்கிறேன்.'], ['I speak Tamil.', 'நான் தமிழ் பேசுகிறேன்.'], ['I like this book.', 'எனக்கு இந்தப் புத்தகம் பிடிக்கும்.']] },
    { word: 'You', split: 'You', tamilSound: 'யூ', tamil: 'நீ / நீங்கள்', meaning: 'The person or people you are speaking to.', kind: 'Pronoun', emoji: '🫵', examples: [['You are kind.', 'நீங்கள் அன்பானவர்.'], ['Are you ready?', 'நீங்கள் தயாரா?'], ['I can help you.', 'நான் உங்களுக்கு உதவ முடியும்.']] },
    { word: 'He', split: 'He', tamilSound: 'ஹீ', tamil: 'அவன் / அவர்', meaning: 'A male person already mentioned.', kind: 'Pronoun', emoji: '👨', examples: [['He is my brother.', 'அவன் என் சகோதரன்.'], ['He is at home.', 'அவர் வீட்டில் இருக்கிறார்.'], ['He can cook.', 'அவரால் சமைக்க முடியும்.']] },
    { word: 'She', split: 'She', tamilSound: 'ஷீ', tamil: 'அவள் / அவர்', meaning: 'A female person already mentioned.', kind: 'Pronoun', emoji: '👩', examples: [['She is my sister.', 'அவள் என் சகோதரி.'], ['She is a doctor.', 'அவர் ஒரு மருத்துவர்.'], ['She reads every day.', 'அவள் தினமும் படிக்கிறாள்.']] },
    { word: 'It', split: 'It', tamilSound: 'இட்', tamil: 'அது', meaning: 'A thing, animal, place, or idea already mentioned.', kind: 'Pronoun', emoji: '📦', examples: [['It is a book.', 'அது ஒரு புத்தகம்.'], ['It is very hot.', 'மிகவும் சூடாக இருக்கிறது.'], ['I like it.', 'எனக்கு அது பிடிக்கும்.']] },
    { word: 'We', split: 'We', tamilSound: 'வீ', tamil: 'நாம் / நாங்கள்', meaning: 'The speaker together with other people.', kind: 'Pronoun', emoji: '🧑‍🤝‍🧑', examples: [['We are a family.', 'நாங்கள் ஒரு குடும்பம்.'], ['We can go now.', 'நாம் இப்போது போகலாம்.'], ['We eat together.', 'நாங்கள் ஒன்றாகச் சாப்பிடுகிறோம்.']] },
    { word: 'They', split: 'They', tamilSound: 'தேய்', tamil: 'அவர்கள் / அவை', meaning: 'Two or more people or things already mentioned.', kind: 'Pronoun', emoji: '👨‍👩‍👧', examples: [['They are my friends.', 'அவர்கள் என் நண்பர்கள்.'], ['They live near here.', 'அவர்கள் இங்கே அருகில் வசிக்கிறார்கள்.'], ['They are ready.', 'அவர்கள் தயாராக இருக்கிறார்கள்.']] },
    { word: 'Me', split: 'Me', tamilSound: 'மீ', tamil: 'என்னை / எனக்கு', meaning: 'The speaker when an action is done to them.', kind: 'Pronoun', emoji: '😊', examples: [['Please help me.', 'தயவுசெய்து எனக்கு உதவுங்கள்.'], ['She called me.', 'அவள் என்னை அழைத்தாள்.'], ['Come with me.', 'என்னுடன் வாருங்கள்.']] },
    { word: 'Him', split: 'Him', tamilSound: 'ஹிம்', tamil: 'அவனை / அவரை', meaning: 'A male person receiving an action.', kind: 'Pronoun', emoji: '👦', examples: [['I know him.', 'எனக்கு அவரைத் தெரியும்.'], ['Please call him.', 'தயவுசெய்து அவரை அழையுங்கள்.'], ['Give the book to him.', 'புத்தகத்தை அவரிடம் கொடுங்கள்.']] },
    { word: 'Her', split: 'Her', tamilSound: 'ஹர்', tamil: 'அவளை / அவரை', meaning: 'A female person receiving an action.', kind: 'Pronoun', emoji: '👧', examples: [['I know her.', 'எனக்கு அவரைத் தெரியும்.'], ['Please help her.', 'தயவுசெய்து அவளுக்கு உதவுங்கள்.'], ['I spoke to her.', 'நான் அவரிடம் பேசினேன்.']] },
    { word: 'Us', split: 'Us', tamilSound: 'அஸ்', tamil: 'எங்களை / நமக்கு', meaning: 'The speaker and others receiving an action.', kind: 'Pronoun', emoji: '🤗', examples: [['Please join us.', 'தயவுசெய்து எங்களுடன் சேருங்கள்.'], ['She called us.', 'அவள் எங்களை அழைத்தாள்.'], ['This will help us.', 'இது நமக்கு உதவும்.']] },
    { word: 'Them', split: 'Them', tamilSound: 'தெம்', tamil: 'அவர்களை / அவற்றை', meaning: 'Other people or things receiving an action.', kind: 'Pronoun', emoji: '👪', examples: [['I can see them.', 'நான் அவர்களைப் பார்க்க முடியும்.'], ['Please call them.', 'தயவுசெய்து அவர்களை அழையுங்கள்.'], ['Give the food to them.', 'அவர்களுக்கு உணவைக் கொடுங்கள்.']] },
  ]},
  { id: 'pointing', name: 'This, That & Quantity', tamil: 'சுட்டும் அளவும்', emoji: '👉', color: '#4f9676', words: [
    { word: 'This', split: 'This', tamilSound: 'திஸ்', tamil: 'இது / இந்த', meaning: 'One person or thing that is near you.', kind: 'Demonstrative', emoji: '👇', examples: [['This is my bag.', 'இது என் பை.'], ['This book is good.', 'இந்தப் புத்தகம் நன்றாக உள்ளது.'], ['I like this colour.', 'எனக்கு இந்த நிறம் பிடிக்கும்.']] },
    { word: 'That', split: 'That', tamilSound: 'தட்', tamil: 'அது / அந்த', meaning: 'One person or thing farther away.', kind: 'Demonstrative', emoji: '👉', examples: [['That is my house.', 'அது என் வீடு.'], ['That road is long.', 'அந்தச் சாலை நீளமானது.'], ['Who is that?', 'அது யார்?']] },
    { word: 'These', split: 'These', tamilSound: 'தீஸ்', tamil: 'இவை / இந்த', meaning: 'More than one thing that is near you.', kind: 'Demonstrative', emoji: '🍎🍎', examples: [['These are fresh.', 'இவை புதியவை.'], ['These books are mine.', 'இந்தப் புத்தகங்கள் என்னுடையவை.'], ['I like these flowers.', 'எனக்கு இந்தப் பூக்கள் பிடிக்கும்.']] },
    { word: 'Those', split: 'Those', tamilSound: 'தோஸ்', tamil: 'அவை / அந்த', meaning: 'More than one thing farther away.', kind: 'Demonstrative', emoji: '🏠🏠', examples: [['Those are my shoes.', 'அவை என் காலணிகள்.'], ['Those houses are new.', 'அந்த வீடுகள் புதியவை.'], ['Who are those people?', 'அந்த மக்கள் யார்?']] },
    { word: 'All', split: 'All', tamilSound: 'ஆல்', tamil: 'அனைத்தும் / எல்லோரும்', meaning: 'Every person or thing in a group.', kind: 'Quantity word', emoji: '🌐', examples: [['All the doors are open.', 'எல்லா கதவுகளும் திறந்திருக்கின்றன.'], ['We are all ready.', 'நாங்கள் அனைவரும் தயாராக இருக்கிறோம்.'], ['I ate all the food.', 'நான் எல்லா உணவையும் சாப்பிட்டேன்.']] },
    { word: 'Some', split: 'Some', tamilSound: 'சம்', tamil: 'சில / கொஞ்சம்', meaning: 'An amount or number, but not all.', kind: 'Quantity word', emoji: '🍪', examples: [['I need some water.', 'எனக்கு கொஞ்சம் தண்ணீர் வேண்டும்.'], ['Some people are here.', 'சிலர் இங்கே இருக்கிறார்கள்.'], ['Please take some rice.', 'கொஞ்சம் சாதம் எடுத்துக்கொள்ளுங்கள்.']] },
    { word: 'Any', split: 'An-y', tamilSound: 'எனி', tamil: 'ஏதேனும் / எதுவும்', meaning: 'One or more, without saying exactly which.', kind: 'Quantity word', emoji: '🎲', examples: [['Do you have any questions?', 'உங்களிடம் ஏதேனும் கேள்விகள் உள்ளதா?'], ['Choose any colour.', 'எந்த நிறத்தையும் தேர்ந்தெடுங்கள்.'], ['I do not have any money.', 'என்னிடம் பணம் எதுவும் இல்லை.']] },
    { word: 'None', split: 'None', tamilSound: 'நன்', tamil: 'ஒன்றுமில்லை / யாருமில்லை', meaning: 'Not one person or thing.', kind: 'Quantity word', emoji: '⭕', examples: [['None of these are mine.', 'இவற்றில் எதுவும் என்னுடையது இல்லை.'], ['None of us are tired.', 'எங்களில் யாரும் சோர்வாக இல்லை.'], ['There is none left.', 'ஒன்றும் மீதமில்லை.']] },
    { word: 'Each', split: 'Each', tamilSound: 'ஈச்', tamil: 'ஒவ்வொன்றும் / ஒவ்வொருவரும்', meaning: 'Every one considered separately.', kind: 'Quantity word', emoji: '1️⃣', examples: [['Each child has a book.', 'ஒவ்வொரு குழந்தையிடமும் ஒரு புத்தகம் உள்ளது.'], ['Take one each.', 'ஒவ்வொருவரும் ஒன்று எடுத்துக்கொள்ளுங்கள்.'], ['Each room is clean.', 'ஒவ்வொரு அறையும் சுத்தமாக உள்ளது.']] },
    { word: 'Every', split: 'Ev-er-y', tamilSound: 'எவ்-ரி', tamil: 'ஒவ்வொரு / எல்லா', meaning: 'All members of a group, one by one.', kind: 'Quantity word', emoji: '📅', examples: [['I walk every day.', 'நான் தினமும் நடக்கிறேன்.'], ['Every room has a door.', 'ஒவ்வொரு அறைக்கும் ஒரு கதவு உள்ளது.'], ['She knows every word.', 'அவளுக்கு ஒவ்வொரு வார்த்தையும் தெரியும்.']] },
  ]},
  { id: 'be-verbs', name: 'Am, Is & Are', tamil: 'இருத்தல் வினைச்சொற்கள்', emoji: '🔗', color: '#b06e45', words: [
    { word: 'Am', split: 'Am', tamilSound: 'ஆம் / எம்', tamil: 'இருக்கிறேன்', meaning: 'A form of “be” used with I in the present.', kind: 'Be verb', emoji: '🙋', examples: [['I am happy.', 'நான் மகிழ்ச்சியாக இருக்கிறேன்.'], ['I am at home.', 'நான் வீட்டில் இருக்கிறேன்.'], ['I am learning English.', 'நான் ஆங்கிலம் கற்றுக்கொண்டு இருக்கிறேன்.']] },
    { word: 'Is', split: 'Is', tamilSound: 'இஸ்', tamil: 'இருக்கிறது / இருக்கிறார்', meaning: 'A present form of “be” used with he, she, it, or one thing.', kind: 'Be verb', emoji: '1️⃣', examples: [['She is a doctor.', 'அவர் ஒரு மருத்துவர்.'], ['He is at home.', 'அவர் வீட்டில் இருக்கிறார்.'], ['The food is ready.', 'உணவு தயாராக இருக்கிறது.']] },
    { word: 'Are', split: 'Are', tamilSound: 'ஆர்', tamil: 'இருக்கிறீர்கள் / இருக்கிறார்கள்', meaning: 'A present form of “be” used with you, we, they, or many things.', kind: 'Be verb', emoji: '👥', examples: [['You are kind.', 'நீங்கள் அன்பானவர்.'], ['We are ready.', 'நாங்கள் தயாராக இருக்கிறோம்.'], ['They are at the shop.', 'அவர்கள் கடையில் இருக்கிறார்கள்.']] },
    { word: 'Was', split: 'Was', tamilSound: 'வாஸ்', tamil: 'இருந்தேன் / இருந்தது', meaning: 'A past form of “be” used with I, he, she, it, or one thing.', kind: 'Be verb · Past', emoji: '⏮️', examples: [['I was tired.', 'நான் சோர்வாக இருந்தேன்.'], ['She was here.', 'அவர் இங்கே இருந்தார்.'], ['The door was open.', 'கதவு திறந்திருந்தது.']] },
    { word: 'Were', split: 'Were', tamilSound: 'வர்', tamil: 'இருந்தீர்கள் / இருந்தார்கள்', meaning: 'A past form of “be” used with you, we, they, or many things.', kind: 'Be verb · Past', emoji: '👥', examples: [['You were right.', 'நீங்கள் சரியாக இருந்தீர்கள்.'], ['We were at home.', 'நாங்கள் வீட்டில் இருந்தோம்.'], ['They were happy.', 'அவர்கள் மகிழ்ச்சியாக இருந்தார்கள்.']] },
    { word: 'Be', split: 'Be', tamilSound: 'பீ', tamil: 'இரு / இருங்கள்', meaning: 'The basic form used to talk about being or a state.', kind: 'Be verb · Base form', emoji: '🌱', examples: [['Please be calm.', 'தயவுசெய்து அமைதியாக இருங்கள்.'], ['I want to be healthy.', 'நான் ஆரோக்கியமாக இருக்க விரும்புகிறேன்.'], ['Be careful on the road.', 'சாலையில் கவனமாக இருங்கள்.']] },
    { word: 'Been', split: 'Been', tamilSound: 'பீன்', tamil: 'இருந்திருக்கிறேன் / இருந்துள்ளது', meaning: 'A form of “be” usually used after have, has, or had.', kind: 'Be verb · Past participle', emoji: '✅', examples: [['I have been busy.', 'நான் வேலையாக இருந்திருக்கிறேன்.'], ['She has been here before.', 'அவர் முன்பு இங்கே இருந்திருக்கிறார்.'], ['They had been friends.', 'அவர்கள் நண்பர்களாக இருந்திருந்தார்கள்.']] },
    { word: 'Being', split: 'Be-ing', tamilSound: 'பீ-யிங்', tamil: 'இருப்பது / நடந்துகொள்வது', meaning: 'The continuing form of “be”.', kind: 'Be verb · -ing form', emoji: '🔄', examples: [['He is being kind.', 'அவர் அன்பாக நடந்துகொள்கிறார்.'], ['Being healthy is important.', 'ஆரோக்கியமாக இருப்பது முக்கியம்.'], ['Thank you for being here.', 'இங்கே இருப்பதற்கு நன்றி.']] },
  ]},
  { id: 'helping-verbs', name: 'Have, Do & Helpers', tamil: 'துணை வினைச்சொற்கள்', emoji: '🧩', color: '#7664a8', words: [
    { word: 'Have', split: 'Have', tamilSound: 'ஹேவ்', tamil: 'வைத்திருக்கிறேன் / உள்ளது', meaning: 'Used for owning something, or with I, you, we, and they to make some verb forms.', kind: 'Helping verb', emoji: '🤲', examples: [['I have a book.', 'என்னிடம் ஒரு புத்தகம் உள்ளது.'], ['We have some food.', 'எங்களிடம் கொஞ்சம் உணவு உள்ளது.'], ['They have finished.', 'அவர்கள் முடித்துவிட்டார்கள்.']] },
    { word: 'Has', split: 'Has', tamilSound: 'ஹேஸ்', tamil: 'வைத்திருக்கிறார் / உள்ளது', meaning: 'The form of “have” used with he, she, it, or one thing.', kind: 'Helping verb', emoji: '👤', examples: [['She has a car.', 'அவரிடம் ஒரு கார் உள்ளது.'], ['He has finished.', 'அவர் முடித்துவிட்டார்.'], ['The room has a door.', 'அறைக்கு ஒரு கதவு உள்ளது.']] },
    { word: 'Had', split: 'Had', tamilSound: 'ஹேட்', tamil: 'வைத்திருந்தேன் / இருந்தது', meaning: 'The past form of “have”, used with every subject.', kind: 'Helping verb · Past', emoji: '🕰️', examples: [['I had a bicycle.', 'என்னிடம் ஒரு மிதிவண்டி இருந்தது.'], ['She had some water.', 'அவரிடம் கொஞ்சம் தண்ணீர் இருந்தது.'], ['We had finished eating.', 'நாங்கள் சாப்பிட்டு முடித்திருந்தோம்.']] },
    { word: 'Do', split: 'Do', tamilSound: 'டூ', tamil: 'செய் / செய்கிறேன்', meaning: 'To perform an action; also helps make questions with I, you, we, and they.', kind: 'Verb / Helping verb', emoji: '✅', examples: [['I do my work.', 'நான் என் வேலையைச் செய்கிறேன்.'], ['Do you speak English?', 'நீங்கள் ஆங்கிலம் பேசுகிறீர்களா?'], ['What do they need?', 'அவர்களுக்கு என்ன வேண்டும்?']] },
    { word: 'Does', split: 'Does', tamilSound: 'டஸ்', tamil: 'செய்கிறார் / செய்கிறது', meaning: 'The form of “do” used with he, she, it, or one thing.', kind: 'Verb / Helping verb', emoji: '☑️', examples: [['She does her work.', 'அவர் தனது வேலையைச் செய்கிறார்.'], ['Does he cook?', 'அவர் சமைக்கிறாரா?'], ['How does it work?', 'இது எப்படி வேலை செய்கிறது?']] },
    { word: 'Did', split: 'Did', tamilSound: 'டிட்', tamil: 'செய்தேன் / செய்தார்', meaning: 'The past form of “do”, used with every subject.', kind: 'Verb / Helping verb · Past', emoji: '⏪', examples: [['I did my work.', 'நான் என் வேலையைச் செய்தேன்.'], ['Did you call her?', 'நீங்கள் அவரை அழைத்தீர்களா?'], ['What did he say?', 'அவர் என்ன சொன்னார்?']] },
    { word: 'Can', split: 'Can', tamilSound: 'கேன்', tamil: 'முடியும்', meaning: 'Shows ability or asks for permission.', kind: 'Modal helping verb', emoji: '💪', examples: [['I can read English.', 'என்னால் ஆங்கிலம் படிக்க முடியும்.'], ['Can you help me?', 'உங்களால் எனக்கு உதவ முடியுமா?'], ['We can go now.', 'நாம் இப்போது போகலாம்.']] },
    { word: 'Could', split: 'Could', tamilSound: 'குட்', tamil: 'முடிந்தது / முடியுமா', meaning: 'Shows past ability or makes a polite request.', kind: 'Modal helping verb', emoji: '🙏', examples: [['I could walk then.', 'அப்போது என்னால் நடக்க முடிந்தது.'], ['Could you help me?', 'நீங்கள் எனக்கு உதவ முடியுமா?'], ['We could go tomorrow.', 'நாம் நாளை போகலாம்.']] },
    { word: 'Will', split: 'Will', tamilSound: 'வில்', tamil: 'செய்வேன் / நடக்கும்', meaning: 'Shows that something is expected in the future.', kind: 'Modal helping verb', emoji: '🔜', examples: [['I will call you.', 'நான் உங்களை அழைப்பேன்.'], ['She will come tomorrow.', 'அவர் நாளை வருவார்.'], ['It will be ready soon.', 'அது விரைவில் தயாராகிவிடும்.']] },
    { word: 'Would', split: 'Would', tamilSound: 'வுட்', tamil: 'செய்வேன் / விரும்புகிறேன்', meaning: 'Used for polite requests, preferences, or imagined situations.', kind: 'Modal helping verb', emoji: '💭', examples: [['I would like some water.', 'எனக்கு கொஞ்சம் தண்ணீர் வேண்டும்.'], ['Would you help me?', 'நீங்கள் எனக்கு உதவுவீர்களா?'], ['She would come if she could.', 'முடிந்தால் அவர் வருவார்.']] },
    { word: 'Should', split: 'Should', tamilSound: 'ஷுட்', tamil: 'வேண்டும் / செய்வது நல்லது', meaning: 'Used to give advice or say what is right.', kind: 'Modal helping verb', emoji: '💡', examples: [['You should rest.', 'நீங்கள் ஓய்வெடுக்க வேண்டும்.'], ['We should eat healthy food.', 'நாம் ஆரோக்கியமான உணவைச் சாப்பிட வேண்டும்.'], ['Should I call him?', 'நான் அவரை அழைக்க வேண்டுமா?']] },
    { word: 'Must', split: 'Must', tamilSound: 'மஸ்ட்', tamil: 'கட்டாயம் வேண்டும்', meaning: 'Shows that something is necessary or very important.', kind: 'Modal helping verb', emoji: '❗', examples: [['You must be careful.', 'நீங்கள் கட்டாயம் கவனமாக இருக்க வேண்டும்.'], ['We must go now.', 'நாம் இப்போது கட்டாயம் செல்ல வேண்டும்.'], ['I must finish this.', 'நான் இதைக் கட்டாயம் முடிக்க வேண்டும்.']] },
  ]},
];

function speak(text: string, slow = false) {
  if (!('speechSynthesis' in window)) return;
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = 'en-IN'; utterance.rate = slow ? 0.58 : 0.82; utterance.pitch = 1;
  window.speechSynthesis.speak(utterance);
}

export default function Home() {
  const [view, setView] = useState<'home' | 'lesson' | 'quiz'>('home');
  const [categoryId, setCategoryId] = useState('food');
  const [wordIndex, setWordIndex] = useState(0);
  const [learned, setLearned] = useState<string[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [largeText, setLargeText] = useState(false);
  const [speechFeedback, setSpeechFeedback] = useState('');
  const [quizFeedback, setQuizFeedback] = useState('');
  useEffect(() => { try { setLearned(JSON.parse(localStorage.getItem('vanakkam-learned') || '[]')); setLargeText(localStorage.getItem('vanakkam-large-text') === 'true'); } catch { setLearned([]); } setLoaded(true); }, []);
  const category = categories.find((item) => item.id === categoryId) || categories[0];
  const word = category.words[wordIndex] || category.words[0];
  const totalWords = categories.reduce((sum, item) => sum + item.words.length, 0);
  const progress = Math.round((learned.length / 500) * 100);
  const learnedInCategory = useMemo(() => category.words.filter((item) => learned.includes(`${category.id}:${item.word}`)).length, [category, learned]);
  void learnedInCategory;

  const openCategory = (id: string) => { const nextCategory = categories.find((item) => item.id === id)!; const firstNew = nextCategory.words.findIndex((item) => !learned.includes(`${id}:${item.word}`)); setCategoryId(id); setWordIndex(firstNew < 0 ? 0 : firstNew); setView('lesson'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const toggleLearned = () => { const key = `${category.id}:${word.word}`; const next = learned.includes(key) ? learned.filter((item) => item !== key) : [...learned, key]; setLearned(next); localStorage.setItem('vanakkam-learned', JSON.stringify(next)); };
  const nextWord = () => { if (wordIndex === 4) { setQuizFeedback(''); setView('quiz'); } else if (wordIndex < category.words.length - 1) setWordIndex(wordIndex + 1); else setView('home'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const toggleTextSize = () => { const next = !largeText; setLargeText(next); localStorage.setItem('vanakkam-large-text', String(next)); };
  const practiceSpeech = () => {
    setSpeechFeedback('கேட்கிறேன்… இப்போது சொல்லுங்கள்');
    const speechWindow = window as typeof window & { webkitSpeechRecognition?: new () => { lang: string; interimResults: boolean; start: () => void; onresult: (event: { results: { 0: { 0: { transcript: string } } }[] }) => void; onerror: () => void } };
    if (!speechWindow.webkitSpeechRecognition) { setSpeechFeedback('இந்த சாதனத்தில் பேசும் பயிற்சி கிடைக்கவில்லை. கேட்டு மீண்டும் சொல்லுங்கள்.'); speak(word.word, true); return; }
    const recognition = new speechWindow.webkitSpeechRecognition(); recognition.lang = 'en-IN'; recognition.interimResults = false;
    recognition.onresult = (event) => { const heard = event.results[0][0].transcript.toLowerCase().trim(); setSpeechFeedback(heard.includes(word.word.toLowerCase()) ? 'மிக நன்று! சரியாகச் சொன்னீர்கள்! ✓' : `“${heard}” என்று கேட்டது. இன்னும் ஒருமுறை முயற்சி செய்யலாம்.`); };
    recognition.onerror = () => setSpeechFeedback('பரவாயில்லை. கேட்டு இன்னும் ஒருமுறை முயற்சி செய்யுங்கள்.'); recognition.start();
  };

  if (view === 'quiz') {
    const quizWord = category.words[4];
    const options = [quizWord, category.words[1], category.words[3]];
    return <main className={`app-shell quiz-shell ${largeText ? 'large-text' : ''}`}>
      <header className="topbar home-topbar"><button className="brand" onClick={() => setView('home')}><span className="brand-mark">வ</span><span><b>வணக்கம் English</b><small>சிறிய மறுபயிற்சி</small></span></button><button className="home-button" onClick={() => setView('home')}>⌂ <span>முகப்பு</span></button></header>
      <section className="quiz-card"><span className="quiz-badge">5 வார்த்தைகள் முடிந்தது! · QUICK REVIEW</span><div className="quiz-celebrate">🌟</div><h1>“{quizWord.word}” என்பதன்<br/>தமிழ் பொருள் என்ன?</h1><button className="quiz-listen" onClick={() => speak(quizWord.word, true)}>🔊 வார்த்தையை கேளுங்கள்</button>
        <div className="quiz-options">{options.map((option) => <button key={option.word} disabled={!!quizFeedback} onClick={() => setQuizFeedback(option.word === quizWord.word ? 'சரியான பதில்! மிக நன்று! ✓' : `இன்னும் கொஞ்சம் முயற்சி செய்வோம். சரியான பதில்: ${quizWord.tamil}`)}><span>{option.emoji}</span>{option.tamil}</button>)}</div>
        {quizFeedback && <div className={`quiz-feedback ${quizFeedback.includes('சரியான') ? 'correct' : ''}`} role="status">{quizFeedback}<button onClick={() => { setWordIndex(5); setView('lesson'); }}>அடுத்த வார்த்தை →</button></div>}
      </section>
    </main>;
  }

  if (view === 'lesson') {
    const isLearned = learned.includes(`${category.id}:${word.word}`);
    return <main className={`app-shell lesson-shell ${largeText ? 'large-text' : ''}`}>
      <header className="topbar">
        <button className="brand" onClick={() => setView('home')} aria-label="முகப்பு பக்கத்திற்குச் செல்லவும்"><span className="brand-mark">வ</span><span><b>வணக்கம் English</b><small>ஒவ்வொரு நாளும் ஒரு சிறிய முன்னேற்றம்</small></span></button>
        <div className="lesson-progress"><span>{category.tamil}</span><div><i style={{ width: `${((wordIndex + 1) / category.words.length) * 100}%` }} /></div><b>{wordIndex + 1} / {category.words.length}</b></div>
        <button className="home-button" onClick={() => setView('home')}>⌂ <span>முகப்பு</span></button>
      </header>
      <section className="lesson-wrap">
        <div className="word-visual" aria-label={`Picture for ${word.word}`}><span className="picture-label">படம் · PICTURE</span><div className="big-emoji" role="img" aria-label={word.word}>{word.emoji}</div><span className="visual-word">{word.word}</span></div>
        <article className="word-card">
          <div className="word-heading"><div><span className="eyebrow">இன்றைய வார்த்தை · TODAY’S WORD</span><h1>{word.word}</h1><p className="split-word">{word.split}</p><p className="tamil-sound">தமிழில் உச்சரிப்பு: <b>{word.tamilSound}</b></p></div>
            <div className="speech-buttons"><button onClick={() => speak(word.word)}><span>🔊</span> கேளுங்கள்<small>Listen</small></button><button onClick={() => speak(word.word, true)}><span>🐢</span> மெதுவாக<small>Slow</small></button></div></div>
          <div className="meaning-grid"><div className="tamil-meaning"><span>தமிழ் பொருள்</span><strong>{word.tamil}</strong></div><div><span>Simple English</span><strong>{word.meaning}</strong><small>{word.kind}</small></div></div>
          <section className="examples"><div className="section-title"><span>பயன்படுத்திப் பார்ப்போம்</span><b>Let’s use the word</b></div>{word.examples.map(([english, tamil], index) => <div className="example-row" key={english}><span className="example-number">{index + 1}</span><div><p>{english}</p><span>{tamil}</span></div><button onClick={() => speak(english, true)} aria-label={`Listen to: ${english}`}>🔊</button></div>)}</section>
          <section className="speak-practice"><div><span>🎙️ பேசிப் பழகுங்கள்</span><small>Speak the word aloud</small></div><button onClick={practiceSpeech}>மைக் அழுத்திப் பேசுங்கள்</button>{speechFeedback && <p role="status">{speechFeedback}</p>}</section>
        </article>
      </section>
      <nav className="lesson-actions"><button className="previous" disabled={wordIndex === 0} onClick={() => setWordIndex(Math.max(0, wordIndex - 1))}>← <span>முந்தையது<small>Previous</small></span></button><button className={`learned-button ${isLearned ? 'done' : ''}`} onClick={toggleLearned}>{isLearned ? '✓' : '○'} <span>{isLearned ? 'கற்றுக்கொண்டேன்!' : 'கற்றதாகக் குறி'}<small>{isLearned ? 'Learned' : 'Mark as learned'}</small></span></button><button className="next" onClick={nextWord}><span>{wordIndex === category.words.length - 1 ? 'முடிக்கவும்' : 'அடுத்தது'}<small>{wordIndex === category.words.length - 1 ? 'Finish' : 'Next word'}</small></span> →</button></nav>
    </main>;
  }

  return <main className={`app-shell ${largeText ? 'large-text' : ''}`}>
    <header className="topbar home-topbar"><div className="brand static"><span className="brand-mark">வ</span><span><b>வணக்கம் English</b><small>தமிழில் எளிதாக ஆங்கிலம் கற்போம்</small></span></div><div className="top-actions"><button aria-label="Text size" aria-pressed={largeText} onClick={toggleTextSize}>அ A</button><button aria-label="Test sound" onClick={() => speak('Welcome. Let us learn English.')}>🔊</button></div></header>
    <section className="welcome"><div><span className="eyebrow">வணக்கம்! இன்று கற்கத் தயாரா?</span><h1>சிறு சிறு வார்த்தைகள்.<br/><em>பெரிய தன்னம்பிக்கை.</em></h1><p>தினமும் 5 வார்த்தைகள் கற்போம். கேளுங்கள், படியுங்கள், நம்பிக்கையுடன் பேசுங்கள்.</p><button className="primary-cta" onClick={() => openCategory('food')}>இன்றைய பாடத்தை தொடங்குங்கள் <span>→</span><small>Start today’s lesson</small></button></div><div className="daily-card"><span className="sun">☀️</span><div><small>இன்றைய இலக்கு</small><b>5 வார்த்தைகள்</b><span>Daily goal</span></div><div className="goal-ring"><strong>{learned.length}</strong><span>/ 5</span></div></div></section>
    <section className="progress-strip"><div><span className="progress-icon">🌱</span><p><small>மொத்த முன்னேற்றம்</small><b>{loaded ? learned.length : 0} <span>/ 500 வார்த்தைகள்</span></b></p></div><div className="wide-progress"><i style={{ width: `${progress}%` }} /></div><p className="encouragement">{learned.length ? 'அருமையான முன்னேற்றம்!' : 'முதல் வார்த்தையிலிருந்து தொடங்கலாம்!'}<small>{learned.length ? 'Wonderful progress!' : 'Let’s begin with the first word!'}</small></p></section>
    <section className="categories-section"><div className="section-heading"><div><span className="eyebrow">உங்களுக்கு பிடித்த தலைப்பை தேர்ந்தெடுங்கள்</span><h2>வகைகள் <em>· Categories</em></h2></div><span>{totalWords} பாட வார்த்தைகள் தயாராக உள்ளன</span></div><div className="category-grid">{categories.map((item) => { const count = item.words.filter((entry) => learned.includes(`${item.id}:${entry.word}`)).length; return <button className="category-card" style={{ '--accent': item.color } as React.CSSProperties} key={item.id} onClick={() => openCategory(item.id)}><span className="category-emoji">{item.emoji}</span><span className="category-copy"><strong>{item.tamil}</strong><b>{item.name}</b><small>{item.words.length} வார்த்தைகள் · {count} முடிந்தது</small></span><span className="category-arrow">→</span><span className="category-progress"><i style={{ width: `${(count / item.words.length) * 100}%` }} /></span></button>; })}</div></section>
    <footer><span>வணக்கம் English</span><p>மெதுவாக கற்போம். நம்பிக்கையுடன் பேசுவோம்.</p><small>Learn gently. Speak confidently.</small></footer>
  </main>;
}
