type Example = [string, string];

const lesson = (word: string, split: string, tamilSound: string, tamil: string, meaning: string, kind: string, emoji: string, examples: Example[]) => ({ word, split, tamilSound, tamil, meaning, kind, emoji, examples });

export const prepositionLessonCategories = [
  { id: 'lesson-also', section: 'lesson-notes' as const, name: 'Using “Also”', tamil: '“Also” பயன்பாடு', emoji: '➕', color: '#6f7fb7', words: [
    lesson('Also', 'Al-so', 'ஆல்-சோ', 'மேலும் / கூட', '“Also” adds another person, thing, or fact. Put it before a main verb, but after a form of “be”.', 'Adverb · Word order', '➕', [
      ['He also wants to join us.', 'அவரும் எங்களுடன் சேர விரும்புகிறார்.'],
      ['He is also with me.', 'அவரும் என்னுடன் இருக்கிறார்.'],
      ['I also want to buy a new bike.', 'நானும் ஒரு புதிய மிதிவண்டி வாங்க விரும்புகிறேன்.'],
      ['She is also at college.', 'அவரும் கல்லூரியில் இருக்கிறார்.'],
      ['The dog is also a good friend of man.', 'நாயும் மனிதனின் நல்ல நண்பனாகும்.'],
      ['I am also tired.', 'நானும் சோர்வாக இருக்கிறேன்.'],
      ['I am also speaking English well after practising.', 'பயிற்சி செய்த பிறகு நானும் ஆங்கிலத்தை நன்றாகப் பேசுகிறேன்.'],
      ['Anuradha also comes at 2:30.', 'அனுராதாவும் 2:30 மணிக்கு வருகிறார்.'],
      ['Geetha also speaks Tamil.', 'கீதாவும் தமிழ் பேசுகிறார்.'],
      ['Joel also joined the class in August.', 'ஜோயலும் ஆகஸ்ட் மாதத்தில் வகுப்பில் சேர்ந்தார்.'],
    ]),
  ]},
  { id: 'lesson-preposition-types', section: 'lesson-notes' as const, name: 'Prepositions & Their Types', tamil: 'முன்னிடைச் சொற்களின் வகைகள்', emoji: '🧭', color: '#4c8c85', words: [
    lesson('What is a Preposition?', 'Prep-o-si-tion', 'ப்ரெப்-அ-ஸி-ஷன்', 'முன்னிடைச் சொல்', 'A preposition comes before a noun, pronoun, or noun phrase to show time, place, direction, location, or another relationship. Common prepositions include above, across, against, along, among, around, at, before, behind, below, beneath, beside, between, by, down, from, in, into, near, of, off, on, to, toward, under, upon, with, and within.', 'Prepositions · Introduction', '📍', [
      ['He sat on the chair.', 'அவர் நாற்காலியில் அமர்ந்தார்.'], ['There is some milk in the fridge.', 'குளிர்சாதனப் பெட்டியில் கொஞ்சம் பால் உள்ளது.'], ['She was hiding under the table.', 'அவர் மேசையின் கீழே ஒளிந்திருந்தார்.'], ['The cat jumped off the counter.', 'பூனை மேடையிலிருந்து கீழே குதித்தது.'], ['Barry drove over the bridge.', 'பாரி பாலத்தின் மேல் வண்டி ஓட்டினார்.'], ['Matilde lost her ring at the beach.', 'மட்டில்டே கடற்கரையில் தனது மோதிரத்தைத் தொலைத்தார்.'], ['The book belongs to Anthony.', 'அந்தப் புத்தகம் ஆண்டனிக்குச் சொந்தமானது.'], ['They were sitting by the tree.', 'அவர்கள் மரத்தருகே அமர்ந்திருந்தார்கள்.'],
    ]),
    lesson('Prepositions of Time', 'Time', 'டைம்', 'நேர முன்னிடைச் சொற்கள்', 'These prepositions show when something happens.', 'Preposition type', '🕐', [['We will be meeting on Friday.', 'நாம் வெள்ளிக்கிழமை சந்திப்போம்.'], ['The supermarket will be closed from 9 p.m. to 9 a.m.', 'பல்பொருள் அங்காடி இரவு 9 மணி முதல் காலை 9 மணி வரை மூடப்பட்டிருக்கும்.'], ['Can you come after some time?', 'சிறிது நேரத்திற்குப் பிறகு வர முடியுமா?'], ['We have been asked to work from home until the end of May.', 'மே மாத இறுதி வரை வீட்டிலிருந்து வேலை செய்யும்படி கேட்டுள்ளனர்.']]),
    lesson('Prepositions of Place', 'Place', 'ப்ளேஸ்', 'இட முன்னிடைச் சொற்கள்', 'These prepositions show the place or position of something.', 'Preposition type', '🗺️', [['I have kept the book I borrowed from you on the table.', 'உங்களிடம் கடன் வாங்கிய புத்தகத்தை மேசையின் மேல் வைத்துள்ளேன்.'], ['Henry hid behind the door.', 'ஹென்றி கதவுக்குப் பின்னால் ஒளிந்தார்.'], ['The dog jumped over the fence.', 'நாய் வேலியைத் தாண்டிக் குதித்தது.'], ['Can you place the red roses between the white daisies?', 'சிவப்பு ரோஜாக்களை வெள்ளை டெய்சி மலர்களுக்கு இடையில் வைக்க முடியுமா?']]),
    lesson('Prepositions of Direction', 'Di-rec-tion', 'டை-ரெக்-ஷன்', 'திசை முன்னிடைச் சொற்கள்', 'These prepositions show the direction in which someone or something moves.', 'Preposition type', '➡️', [['The girl ran toward her father the moment she saw him.', 'தந்தையைப் பார்த்தவுடன் சிறுமி அவரை நோக்கி ஓடினாள்.'], ['Jerry jumped into the river to help his sister.', 'தங்கைக்கு உதவ ஜெர்ரி ஆற்றுக்குள் குதித்தார்.'], ['Veena passed the book to Priya.', 'வீணா புத்தகத்தை பிரியாவிடம் கொடுத்தார்.'], ['When will Salvia be returning from London?', 'சால்வியா லண்டனிலிருந்து எப்போது திரும்புவார்?']]),
    lesson('Prepositions of Location', 'Lo-ca-tion', 'லோ-கே-ஷன்', 'இருப்பிட முன்னிடைச் சொற்கள்', 'These prepositions identify the location of a person or object.', 'Preposition type', '🏠', [['Kenny will be staying at his cousin’s place for the weekend.', 'கென்னி வார இறுதியில் உறவினர் வீட்டில் தங்குவார்.'], ['Make sure you put all the toys back in their place after you play.', 'விளையாடிய பிறகு பொம்மைகளை அவற்றின் இடத்தில் வையுங்கள்.'], ['I lay on the floor for a really long time.', 'நான் நீண்ட நேரம் தரையில் படுத்திருந்தேன்.']]),
    lesson('Spatial Relationships', 'Spa-tial Re-la-tion-ships', 'ஸ்பே-ஷல் ரி-லே-ஷன்-ஷிப்ஸ்', 'இடவியல் தொடர்புகள்', 'These prepositions show how one object is positioned in relation to another.', 'Preposition type', '↔️', [['Navya sat leaning against the wall.', 'நவ்யா சுவரில் சாய்ந்து அமர்ந்தார்.'], ['The circus was stationed opposite the children’s park.', 'சர்க்கஸ் குழந்தைகள் பூங்காவுக்கு எதிரில் அமைந்திருந்தது.'], ['Lakshmi sat beneath the trees.', 'லட்சுமி மரங்களின் கீழே அமர்ந்தார்.'], ['Shankar sat beside the stairs.', 'சங்கர் படிக்கட்டுகளின் அருகே அமர்ந்தார்.'], ['We spent the evening walking along the river.', 'நாங்கள் மாலை நேரத்தை ஆற்றங்கரையோரம் நடந்து கழித்தோம்.']]),
  ]},
  { id: 'lesson-by', section: 'lesson-notes' as const, name: 'Uses of “By”', tamil: '“By” பயன்பாடுகள்', emoji: '📌', color: '#b07354', words: [
    lesson('1. The Doer', 'By + do-er', 'பை', 'செய்பவரைக் காட்டுதல்', 'Use “by” in a passive sentence to identify the person who performs an action.', 'By · Agent', '✍️', [['The letter was written by Ravi.', 'கடிதம் ரவியால் எழுதப்பட்டது.'], ['The cake was made by my mother.', 'கேக் என் அம்மாவால் செய்யப்பட்டது.'], ['The poem was written by William Wordsworth.', 'கவிதை வில்லியம் வேர்ட்ஸ்வொர்த்தால் எழுதப்பட்டது.'], ['The house was painted by the workers.', 'வீடு தொழிலாளர்களால் வண்ணம் பூசப்பட்டது.']]),
    lesson('2. A Deadline', 'By + time', 'பை', 'காலக்கெடு', '“By” means before or no later than a particular time.', 'By · Time', '⏰', [['Please finish your homework by 7 p.m.', 'இரவு 7 மணிக்குள் வீட்டுப்பாடத்தை முடிக்கவும்.'], ['I will complete the project by Monday.', 'திங்கட்கிழமைக்குள் திட்டத்தை முடிப்பேன்.'], ['She will return by tomorrow.', 'அவர் நாளைக்குள் திரும்புவார்.'], ['Submit the form by Friday.', 'வெள்ளிக்கிழமைக்குள் படிவத்தைச் சமர்ப்பிக்கவும்.']]),
    lesson('3. Travel', 'By + transport', 'பை', 'பயண முறை', 'Use “by” before a means of transport. Say “on foot,” not “by foot.”', 'By · Transport', '🚌', [['I go to school by bus.', 'நான் பேருந்தில் பள்ளிக்குச் செல்கிறேன்.'], ['They travelled by train.', 'அவர்கள் ரயிலில் பயணம் செய்தார்கள்.'], ['We went to Delhi by plane.', 'நாங்கள் விமானத்தில் டெல்லிக்குச் சென்றோம்.'], ['He usually travels by car.', 'அவர் வழக்கமாக காரில் பயணம் செய்கிறார்.']]),
    lesson('4. Method or Means', 'By + method', 'பை', 'முறை அல்லது வழி', 'Use “by” to show the method or means used to do something.', 'By · Method', '📧', [['I sent the message by email.', 'நான் மின்னஞ்சல் மூலம் செய்தியை அனுப்பினேன்.'], ['She paid by credit card.', 'அவர் கடன் அட்டையால் பணம் செலுத்தினார்.'], ['He contacted me by phone.', 'அவர் தொலைபேசி மூலம் என்னைத் தொடர்புகொண்டார்.'], ['We learned about the event by watching the news.', 'செய்தியைப் பார்த்து நிகழ்வைப் பற்றி அறிந்தோம்.']]),
    lesson('5. Beside or Near', 'By + place', 'பை', 'அருகில்', 'Use “by” to mean beside or near something.', 'By · Place', '🪟', [['There is a small shop by the road.', 'சாலையருகே ஒரு சிறிய கடை உள்ளது.'], ['She sat by the window.', 'அவர் ஜன்னலருகே அமர்ந்தார்.'], ['The children are playing by the river.', 'குழந்தைகள் ஆற்றருகே விளையாடுகிறார்கள்.'], ['He stood by the door.', 'அவர் கதவருகே நின்றார்.']]),
    lesson('6. Amount of Change', 'Change + by', 'பை', 'மாற்றத்தின் அளவு', 'Use “by” to show the amount by which a number or measurement changes.', 'By · Measurement', '📈', [['The price increased by ₹100.', 'விலை ₹100 உயர்ந்தது.'], ['The temperature dropped by five degrees.', 'வெப்பநிலை ஐந்து டிகிரி குறைந்தது.'], ['The company reduced the price by 20%.', 'நிறுவனம் விலையை 20% குறைத்தது.'], ['The number of students increased by ten.', 'மாணவர்களின் எண்ணிக்கை பத்து அதிகரித்தது.']]),
    lesson('7. How Something Is Done', 'Verb + by', 'பை', 'எப்படிச் செய்யப்படுகிறது', 'Use “by” to explain how an action is done or how something is recognized.', 'By · Manner', '🖐️', [['I know her by her voice.', 'அவரது குரலை வைத்து அவரை அடையாளம் காண்கிறேன்.'], ['He is known by his nickname.', 'அவர் புனைப்பெயரால் அறியப்படுகிறார்.'], ['We usually work by hand.', 'நாங்கள் வழக்கமாக கையால் வேலை செய்கிறோம்.'], ['She learned English by practising every day.', 'அவர் தினமும் பயிற்சி செய்து ஆங்கிலம் கற்றார்.']]),
    lesson('8. Rate or Unit', 'By + unit', 'பை', 'விகிதம் அல்லது அலகு', 'Use “by” with the unit used for selling, paying, or renting.', 'By · Rate', '⚖️', [['Mangoes are sold by the kilogram.', 'மாம்பழங்கள் கிலோ கணக்கில் விற்கப்படுகின்றன.'], ['The workers are paid by the hour.', 'தொழிலாளர்களுக்கு மணிநேரக் கணக்கில் ஊதியம் வழங்கப்படுகிறது.'], ['Eggs are sold by the dozen.', 'முட்டைகள் டஜன் கணக்கில் விற்கப்படுகின்றன.'], ['The car is rented by the day.', 'கார் நாள் கணக்கில் வாடகைக்கு விடப்படுகிறது.']]),
    lesson('9. Common Expressions', 'By + ex-pres-sion', 'பை', 'பொதுவான சொற்றொடர்கள்', 'Learn these useful fixed expressions with “by.”', 'By · Expressions', '💬', [['I took your book by mistake.', 'நான் தவறுதலாக உங்கள் புத்தகத்தை எடுத்தேன்.'], ['I met my old friend by chance.', 'நான் தற்செயலாக பழைய நண்பரைச் சந்தித்தேன்.'], ['She made the card by hand.', 'அவர் அட்டையை கையால் செய்தார்.'], ['Can you do this by yourself?', 'இதை நீங்களே செய்ய முடியுமா?'], ['He learned the poem by heart.', 'அவர் கவிதையை மனப்பாடம் செய்தார்.'], ['By the way, where is your brother?', 'சரி, உங்கள் சகோதரர் எங்கே?']]),
  ]},
  { id: 'lesson-for', section: 'lesson-notes' as const, name: 'Uses of “For”', tamil: '“For” பயன்பாடுகள்', emoji: '🎯', color: '#9a6c98', words: [
    lesson('1. Purpose', 'For + purpose', 'ஃபார்', 'நோக்கம்', 'Use “for” to say what or whom something is intended for.', 'For · Purpose', '🎯', [['This book is for children.', 'இந்தப் புத்தகம் குழந்தைகளுக்கானது.'], ['I bought a gift for my mother.', 'என் அம்மாவுக்காக ஒரு பரிசு வாங்கினேன்.'], ['This room is for meetings.', 'இந்த அறை கூட்டங்களுக்கானது.'], ['We use a pen for writing.', 'எழுதுவதற்கு பேனாவைப் பயன்படுத்துகிறோம்.']]),
    lesson('2. Duration', 'For + period', 'ஃபார்', 'கால அளவு', 'Use “for” with a length of time.', 'For · Time', '⌛', [['I have lived here for five years.', 'நான் ஐந்து ஆண்டுகளாக இங்கே வசிக்கிறேன்.'], ['She studied for two hours.', 'அவர் இரண்டு மணி நேரம் படித்தார்.'], ['They stayed there for a week.', 'அவர்கள் ஒரு வாரம் அங்கே தங்கினார்கள்.'], ['He waited for ten minutes.', 'அவர் பத்து நிமிடங்கள் காத்திருந்தார்.']]),
    lesson('3. Recipient', 'For + person', 'ஃபார்', 'பெறுபவர்', 'Use “for” to show the person who will receive or benefit from something.', 'For · Recipient', '🎁', [['This letter is for you.', 'இந்தக் கடிதம் உங்களுக்கானது.'], ['I bought flowers for my teacher.', 'என் ஆசிரியருக்காக மலர்கள் வாங்கினேன்.'], ['She made tea for her guests.', 'அவர் விருந்தினர்களுக்காக தேநீர் தயாரித்தார்.'], ['He bought a present for his sister.', 'அவர் சகோதரிக்காக ஒரு பரிசு வாங்கினார்.']]),
    lesson('4. Reason', 'For + reason', 'ஃபார்', 'காரணம்', 'Use “for” to introduce a reason.', 'For · Reason', '💡', [['Thank you for your help.', 'உங்கள் உதவிக்கு நன்றி.'], ['She was punished for being late.', 'தாமதமாக வந்ததற்காக அவர் தண்டிக்கப்பட்டார்.'], ['He apologized for his mistake.', 'அவர் தனது தவறுக்காக மன்னிப்பு கேட்டார்.'], ['We thanked him for his kindness.', 'அவரது அன்புக்காக நாங்கள் நன்றி கூறினோம்.']]),
    lesson('5. Destination', 'Leave + for', 'ஃபார்', 'பயண இலக்கு', 'Use “for” after verbs such as leave to show the destination.', 'For · Destination', '🚆', [['We are leaving for Mumbai.', 'நாங்கள் மும்பைக்குப் புறப்படுகிறோம்.'], ['She left for school at 8 a.m.', 'அவர் காலை 8 மணிக்கு பள்ளிக்குப் புறப்பட்டார்.'], ['They are travelling to Delhi tomorrow.', 'அவர்கள் நாளை டெல்லிக்குப் பயணம் செய்கிறார்கள்.']]),
    lesson('6. Suitability', 'For + person/thing', 'ஃபார்', 'பொருத்தம்', 'Use “for” to say that something is suitable, useful, or good for someone.', 'For · Suitability', '✅', [['This dress is perfect for you.', 'இந்த உடை உங்களுக்கு மிகவும் பொருத்தமானது.'], ['Exercise is good for your health.', 'உடற்பயிற்சி உங்கள் உடல்நலத்திற்கு நல்லது.'], ['This book is useful for beginners.', 'இந்தப் புத்தகம் தொடக்கநிலையினருக்கு பயனுள்ளது.'], ['The course is suitable for students.', 'இந்தப் பாடநெறி மாணவர்களுக்கு ஏற்றது.']]),
    lesson('7. Exchange or Price', 'For + price', 'ஃபார்', 'விலை அல்லது பரிமாற்றம்', 'Use “for” to show a price or what is received in an exchange.', 'For · Exchange', '💰', [['I bought this book for ₹200.', 'இந்தப் புத்தகத்தை ₹200க்கு வாங்கினேன்.'], ['He sold his bicycle for ₹5,000.', 'அவர் மிதிவண்டியை ₹5,000க்கு விற்றார்.'], ['She exchanged her old phone for a new one.', 'அவர் பழைய தொலைபேசியை புதியதொன்றுடன் மாற்றினார்.']]),
    lesson('8. Common Expressions', 'For + ex-pres-sion', 'ஃபார்', 'பொதுவான சொற்றொடர்கள்', 'Learn these useful fixed expressions with “for.”', 'For · Expressions', '💬', [['For example, you can use this word in a sentence.', 'உதாரணமாக, இந்தச் சொல்லை ஒரு வாக்கியத்தில் பயன்படுத்தலாம்.'], ['Please wait for a while.', 'தயவுசெய்து சிறிது நேரம் காத்திருங்கள்.'], ['I will come for sure.', 'நான் நிச்சயமாக வருவேன்.'], ['This is enough for now.', 'இப்போதைக்கு இது போதும்.'], ['I visited Delhi for the first time.', 'நான் முதல் முறையாக டெல்லிக்குச் சென்றேன்.']]),
  ]},
  { id: 'lesson-of', section: 'lesson-notes' as const, name: 'Uses of “Of”', tamil: '“Of” பயன்பாடுகள்', emoji: '🔗', color: '#557fa1', words: [
    lesson('1. Possession or Belonging', 'Of + owner', 'அவ்', 'உடைமை அல்லது சொந்தம்', '“Of” shows that something belongs to or is connected with someone or something.', 'Of · Possession', '🏠', [['The name of the boy is Rahul.', 'அந்தச் சிறுவனின் பெயர் ராகுல்.'], ['The door of the house is open.', 'வீட்டின் கதவு திறந்துள்ளது.'], ['The colour of the car is blue.', 'காரின் நிறம் நீலம்.'], ['The roof of the building is damaged.', 'கட்டிடத்தின் கூரை சேதமடைந்துள்ளது.'], ['The owner of the shop is very kind.', 'கடையின் உரிமையாளர் மிகவும் அன்பானவர்.'], ['The mother of my friend is a teacher.', 'என் நண்பரின் அம்மா ஒரு ஆசிரியர்.'], ['The capital of India is New Delhi.', 'இந்தியாவின் தலைநகர் புதுடெல்லி.'], ['The pages of the book are torn.', 'புத்தகத்தின் பக்கங்கள் கிழிந்துள்ளன.']]),
    lesson('2. Relationship', 'Noun + of + noun', 'அவ்', 'உறவு', 'Use “of” to show a relationship between people or things.', 'Of · Relationship', '🤝', [['She is a friend of my sister.', 'அவர் என் சகோதரியின் தோழி.'], ['He is a colleague of my father.', 'அவர் என் தந்தையின் சக ஊழியர்.'], ['This is a photograph of my family.', 'இது என் குடும்பத்தின் புகைப்படம்.'], ['He is a student of our school.', 'அவர் எங்கள் பள்ளியின் மாணவர்.'], ['She is a member of the team.', 'அவர் அணியின் உறுப்பினர்.'], ['He is the son of a farmer.', 'அவர் ஒரு விவசாயியின் மகன்.']]),
    lesson('3. Part of Something', 'Part + of + whole', 'அவ்', 'ஒரு பகுதி', 'Use “of” when talking about a part, section, or portion of something.', 'Of · Part', '🍰', [['I ate a piece of cake.', 'நான் ஒரு துண்டு கேக் சாப்பிட்டேன்.'], ['She drank a glass of water.', 'அவர் ஒரு குவளை தண்ணீர் குடித்தார்.'], ['He bought a slice of bread.', 'அவர் ஒரு துண்டு ரொட்டி வாங்கினார்.'], ['I need a piece of paper.', 'எனக்கு ஒரு துண்டு காகிதம் வேண்டும்.'], ['She gave me a bottle of juice.', 'அவர் எனக்கு ஒரு பாட்டில் பழச்சாறு கொடுத்தார்.'], ['He took a part of the money.', 'அவர் பணத்தின் ஒரு பகுதியை எடுத்தார்.'], ['A corner of the room is empty.', 'அறையின் ஒரு மூலை காலியாக உள்ளது.'], ['The top of the mountain is covered with snow.', 'மலையின் உச்சி பனியால் மூடப்பட்டுள்ளது.']]),
    lesson('4. Quantity or Amount', 'Quantity + of', 'அவ்', 'அளவு', 'Use “of” after quantity words such as a lot, cup, bottle, piece, kilo, group, pair, and bunch.', 'Of · Quantity', '🔢', [['A lot of students attended the class.', 'நிறைய மாணவர்கள் வகுப்பில் கலந்துகொண்டனர்.'], ['A cup of tea is on the table.', 'மேசையின் மேல் ஒரு கோப்பை தேநீர் உள்ளது.'], ['A kilo of rice is enough.', 'ஒரு கிலோ அரிசி போதும்.'], ['A bottle of milk is in the fridge.', 'குளிர்சாதனப் பெட்டியில் ஒரு பாட்டில் பால் உள்ளது.'], ['A group of children is playing outside.', 'ஒரு குழு குழந்தைகள் வெளியே விளையாடுகிறது.'], ['A number of people attended the meeting.', 'பலர் கூட்டத்தில் கலந்துகொண்டனர்.'], ['A pair of shoes is under the bed.', 'ஒரு ஜோடி காலணிகள் படுக்கையின் கீழே உள்ளன.'], ['A bunch of grapes is on the table.', 'மேசையின் மேல் ஒரு கொத்து திராட்சை உள்ளது.']]),
    lesson('5. Material or Substance', 'Made of + material', 'அவ்', 'பொருள் அல்லது மூலப்பொருள்', '“Made of” tells us the material when the original material is still recognizable.', 'Of · Material', '🪵', [['The table is made of wood.', 'மேசை மரத்தால் செய்யப்பட்டது.'], ['The ring is made of gold.', 'மோதிரம் தங்கத்தால் செய்யப்பட்டது.'], ['The chair is made of plastic.', 'நாற்காலி பிளாஸ்டிக்கால் செய்யப்பட்டது.'], ['The house is made of stone.', 'வீடு கல்லால் கட்டப்பட்டது.'], ['This necklace is made of silver.', 'இந்த மாலை வெள்ளியால் செய்யப்பட்டது.']]),
    lesson('6. Origin or Source', 'Of + origin', 'அவ்', 'தோற்றம் அல்லது மூலம்', 'Use “of” to indicate where someone or something comes from or is associated with.', 'Of · Origin', '🌍', [['He is a man of Indian origin.', 'அவர் இந்திய வம்சாவளியைச் சேர்ந்தவர்.'], ['She is a woman of great talent.', 'அவர் மிகுந்த திறமை கொண்டவர்.'], ['He is a person of courage.', 'அவர் துணிச்சல் கொண்டவர்.'], ['The story is of British origin.', 'இந்தக் கதை பிரிட்டிஷ் தோற்றம் கொண்டது.'], ['This is a tradition of ancient India.', 'இது பண்டைய இந்தியாவின் பாரம்பரியம்.']]),
    lesson('7. Qualities', 'Person + of + quality', 'அவ்', 'குணங்கள்', 'Use “of” to describe a person’s quality or characteristic.', 'Of · Quality', '⭐', [['She is a woman of courage.', 'அவர் துணிச்சலான பெண்.'], ['He is a man of honesty.', 'அவர் நேர்மையான மனிதர்.'], ['She is a person of great intelligence.', 'அவர் மிகுந்த அறிவாற்றல் கொண்டவர்.'], ['He is a person of strong character.', 'அவர் உறுதியான குணம் கொண்டவர்.'], ['She is a woman of determination.', 'அவர் மனஉறுதி கொண்ட பெண்.']]),
    lesson('8. After Adjectives', 'Adjective + of', 'அவ்', 'பெயரடைக்குப் பிறகு', 'Some adjectives are commonly followed by “of”: afraid, proud, tired, full, fond, aware, capable, jealous, sure, and ashamed.', 'Of · Adjectives', '🧩', [['She is afraid of dogs.', 'அவர் நாய்களுக்குப் பயப்படுகிறார்.'], ['I am proud of my brother.', 'என் சகோதரரைப் பற்றி நான் பெருமைப்படுகிறேன்.'], ['He is tired of waiting.', 'அவர் காத்திருப்பதில் சோர்ந்துவிட்டார்.'], ['The glass is full of water.', 'குவளை தண்ணீரால் நிரம்பியுள்ளது.'], ['She is fond of music.', 'அவருக்கு இசை மிகவும் பிடிக்கும்.'], ['Are you aware of the problem?', 'பிரச்சினையை நீங்கள் அறிந்திருக்கிறீர்களா?'], ['He is capable of doing this work.', 'அவரால் இந்த வேலையைச் செய்ய முடியும்.'], ['She is jealous of her friend.', 'அவர் தனது தோழியைப் பார்த்துப் பொறாமைப்படுகிறார்.'], ['I am sure of his success.', 'அவரது வெற்றியில் எனக்கு நம்பிக்கை உள்ளது.'], ['He is ashamed of his mistake.', 'அவர் தனது தவறிற்காக வெட்கப்படுகிறார்.']]),
    lesson('9. After Verbs', 'Verb + of', 'அவ்', 'வினைச்சொல்லுக்குப் பிறகு', 'Some verbs and verb phrases commonly use “of”: think, dream, hear, remind, consist, take care, get rid, and approve.', 'Of · Verbs', '⚙️', [['I often think of my childhood.', 'நான் அடிக்கடி என் குழந்தைப் பருவத்தை நினைக்கிறேன்.'], ['She dreams of becoming a doctor.', 'அவர் மருத்துவராக வேண்டும் என்று கனவு காண்கிறார்.'], ['Have you heard of this place?', 'இந்த இடத்தைப் பற்றி கேள்விப்பட்டிருக்கிறீர்களா?'], ['This song reminds me of my school days.', 'இந்தப் பாடல் என் பள்ளி நாட்களை நினைவூட்டுகிறது.'], ['The team consists of ten players.', 'அணி பத்து வீரர்களைக் கொண்டுள்ளது.'], ['Please take care of your books.', 'உங்கள் புத்தகங்களை கவனித்துக்கொள்ளுங்கள்.'], ['We need to get rid of old clothes.', 'பழைய ஆடைகளை அகற்ற வேண்டும்.'], ["I don't approve of his behaviour.", 'அவரது நடத்தையை நான் ஏற்கவில்லை.']]),
    lesson('10. A Specific Amount', 'Amount + of + group', 'அவ்', 'குறிப்பிட்ட அளவு', 'Use “of” between a number or quantity and a defined group or noun.', 'Of · Amount', '📊', [['Two of my friends are doctors.', 'என் நண்பர்களில் இருவர் மருத்துவர்கள்.'], ['Three of the students were absent.', 'மாணவர்களில் மூவர் வரவில்லை.'], ['Some of the water was spilled.', 'தண்ணீரில் சிறிது சிந்தியது.'], ['Most of the children enjoyed the game.', 'பெரும்பாலான குழந்தைகள் விளையாட்டை ரசித்தனர்.'], ['Half of the cake was eaten.', 'கேக்கில் பாதி சாப்பிடப்பட்டது.'], ['All of the students completed the test.', 'அனைத்து மாணவர்களும் தேர்வை முடித்தனர்.'], ['None of the money was stolen.', 'பணத்தில் எதுவும் திருடப்படவில்லை.']]),
    lesson('11. Dates and Periods', 'Of + period', 'அவ்', 'தேதிகள் மற்றும் காலங்கள்', 'Use “of” in expressions referring to a particular historical period.', 'Of · Period', '📅', [['The events of 1947 are important in Indian history.', '1947ஆம் ஆண்டின் நிகழ்வுகள் இந்திய வரலாற்றில் முக்கியமானவை.'], ['The people of the 19th century lived differently.', '19ஆம் நூற்றாண்டு மக்கள் வேறுவிதமாக வாழ்ந்தனர்.'], ['The history of ancient India is fascinating.', 'பண்டைய இந்தியாவின் வரலாறு சுவாரஸ்யமானது.'], ['The culture of the past was different.', 'கடந்த காலத்தின் கலாசாரம் வேறுபட்டது.']]),
    lesson('12. Characteristic or Type', 'Noun + of + description', 'அவ்', 'தன்மை அல்லது வகை', 'Use “of” to add a characteristic or description to a person, thing, or situation.', 'Of · Description', '🪪', [['He is a person of good manners.', 'அவர் நல்ல பழக்கவழக்கங்கள் கொண்டவர்.'], ['She is a woman of great beauty.', 'அவர் மிகுந்த அழகு கொண்டவர்.'], ['He is a man of few words.', 'அவர் குறைவாகப் பேசும் மனிதர்.'], ['It was a matter of great importance.', 'அது மிக முக்கியமான விஷயம்.'], ['This is a problem of serious concern.', 'இது மிகுந்த கவலைக்குரிய பிரச்சினை.']]),
    lesson('13. Simple Practice', '20 ex-am-ples', 'சிம்பிள் ப்ராக்டிஸ்', '20 எளிய வாக்கியங்கள்', 'Review the main uses of “of” with these short everyday sentences.', 'Of · Review', '🗣️', [['This is the colour of my dress.', 'இது என் உடையின் நிறம்.'], ['I drank a glass of water.', 'நான் ஒரு குவளை தண்ணீர் குடித்தேன்.'], ['She is a friend of mine.', 'அவர் என் தோழி.'], ['He is afraid of dogs.', 'அவர் நாய்களுக்குப் பயப்படுகிறார்.'], ['The door of the room is closed.', 'அறையின் கதவு மூடப்பட்டுள்ளது.'], ['I ate a piece of cake.', 'நான் ஒரு துண்டு கேக் சாப்பிட்டேன்.'], ['She is proud of her son.', 'அவர் தனது மகனைப் பற்றி பெருமைப்படுகிறார்.'], ['The table is made of wood.', 'மேசை மரத்தால் செய்யப்பட்டது.'], ['He is fond of cricket.', 'அவருக்கு கிரிக்கெட் மிகவும் பிடிக்கும்.'], ['Give me a cup of tea.', 'எனக்கு ஒரு கோப்பை தேநீர் கொடுங்கள்.'], ['The capital of India is New Delhi.', 'இந்தியாவின் தலைநகர் புதுடெல்லி.'], ['A group of students is waiting.', 'ஒரு குழு மாணவர்கள் காத்திருக்கிறது.'], ['I am tired of this noise.', 'இந்தச் சத்தத்தால் நான் சோர்ந்துவிட்டேன்.'], ['She dreams of becoming a teacher.', 'அவர் ஆசிரியராக வேண்டும் என்று கனவு காண்கிறார்.'], ['The roof of the house is red.', 'வீட்டின் கூரை சிவப்பு நிறத்தில் உள்ளது.'], ['He is a man of courage.', 'அவர் துணிச்சலான மனிதர்.'], ['Most of the students passed.', 'பெரும்பாலான மாணவர்கள் தேர்ச்சி பெற்றனர்.'], ['Take care of your health.', 'உங்கள் உடல்நலத்தை கவனித்துக்கொள்ளுங்கள்.'], ['The pages of the book are clean.', 'புத்தகத்தின் பக்கங்கள் சுத்தமாக உள்ளன.'], ['She is aware of the problem.', 'அவர் பிரச்சினையை அறிந்திருக்கிறார்.']]),
  ]},
];
